import { effectiveLayerFill } from './layer-fill';
import { supportsMask } from './dense-mask';
import { supportsPhotoFilter, photoFilterCapabilityKey } from './photo-filter';
import { colorLookupCapabilityKey, recipeHasLookup, supportsLookupEntry } from './color-lookup';
import { supportsTargetedHSL, targetedHSLCapabilityKey } from './targeted-hsl';
import { supportsSelectiveColor, selectiveColorCapabilityKey } from './selective-color';
import { supportsCurves, curvesCapabilityKey } from './curves';
import { filterMaskCapabilityKey, supportsFilterMask } from './filter-mask';
import { useEffect, useRef, useState } from 'react';
import { Check, Download, Library, LoaderCircle, RefreshCw, Save, Upload } from 'lucide-react';
import { command, commandWithRequestId, downloadBlob, type Backend, type BackendId, type Document, type EditRecipe, type EditRecipeDefinition, type EditRecipeReport, type Layer } from './api';
import { captureChoices, captureRecipe, parseRecipeFile, recipeCommands, slotMatches } from './recipe-capture';
import { layerAncestors } from './layer-tree';
import './edit-recipes.css';
import { supportsSourceFilterEntry } from './filter-blend';

type ApplyArgs = { documentId: string; expectedRevision: number; recipeId: string; bindings: Record<string, string> };
type Invocation = { requestId: string; args: ApplyArgs; name: string; error?: string; inspected?: boolean };
type Lifecycle = { backend: BackendId; document: Document | null; setBusy: (label: string) => void; reconcile: (document: Document) => Promise<void>; notify: (message: string, error?: boolean) => void };
export function useRecipeApplication(props: Lifecycle) {
  const [pending, setPending] = useState<Invocation | null>(null), [working, setWorking] = useState(false);
  const current = useRef(props); current.current = props; const invocation = useRef<Invocation | null>(null), running = useRef(false);
  const publish = (next: Invocation | null) => { invocation.current = next; setPending(next); };
  const invoke = async (request: Invocation) => {
    if (running.current) return;
    running.current = true; setWorking(true); publish({ ...request, error: undefined }); current.current.setBusy('Applying edit recipe');
    try {
      const result = await commandWithRequestId<{ document: Document; recipeId: string; appliedSteps: number }>('native', 'apply_edit_recipe', request.args, request.requestId);
      if (result.document.id !== request.args.documentId || result.recipeId !== request.args.recipeId || !Number.isInteger(result.appliedSteps)) throw Error('Recipe response did not match this application. Inspect the current document before continuing.');
      // Same-ID replay may return the ORIGINAL response after an Undo or external edit.
      // Reconcile from fresh metadata, never from that potentially older snapshot.
      const fresh = await command<{ document: Document }>('native', 'get_document', { documentId: request.args.documentId });
      await current.current.reconcile(fresh.document);
      if (invocation.current?.requestId === request.requestId) publish(null);
      current.current.notify(`Recipe application confirmed (${result.appliedSteps} ${result.appliedSteps === 1 ? 'step' : 'steps'}). Current document revision ${fresh.document.revision}.`);
    } catch (error) { if (invocation.current?.requestId === request.requestId) publish({ ...request, error: error instanceof Error ? error.message : 'The recipe outcome could not be confirmed.' }); }
    finally { running.current = false; setWorking(false); current.current.setBusy(''); }
  };
  const inspect = async () => {
    const request = invocation.current; if (!request || running.current) return;
    if (current.current.backend !== 'native' || current.current.document?.id !== request.args.documentId) { publish({ ...request, inspected: false, error: 'Return to the original application document to inspect its layers and history.' }); return; }
    running.current = true; setWorking(true); current.current.setBusy('Inspecting recipe outcome');
    try { const fresh = await command<{ document: Document }>('native', 'get_document', { documentId: request.args.documentId }); await current.current.reconcile(fresh.document); if (invocation.current?.requestId === request.requestId) { const sameDocument = current.current.backend === 'native' && current.current.document?.id === request.args.documentId; publish({ ...request, inspected: sameDocument, error: sameDocument ? `Application document revision ${fresh.document.revision} loaded. Review its layers and history before starting another application.` : 'Return to the original application document to inspect its layers and history.' }); } }
    catch (error) { if (invocation.current?.requestId === request.requestId) publish({ ...request, error: error instanceof Error ? error.message : 'Could not inspect the current document.' }); }
    finally { running.current = false; setWorking(false); current.current.setBusy(''); }
  };
  return { pending, working, canInspect: Boolean(pending && props.backend === 'native' && props.document?.id === pending.args.documentId), apply: (args: ApplyArgs, name: string) => { if (invocation.current || running.current) return; if (current.current.backend !== 'native' || current.current.document?.id !== args.documentId || current.current.document.revision !== args.expectedRevision) { current.current.notify('The recipe document changed. Refresh and validate again before applying.', true); return; } void invoke({ requestId: crypto.randomUUID(), args: structuredClone(args), name }); }, retry: () => { if (invocation.current) void invoke(invocation.current); }, inspect, finishReview: () => { if (invocation.current?.inspected && !running.current && current.current.backend === 'native' && current.current.document?.id === invocation.current.args.documentId) publish(null); } };
}
type Application = ReturnType<typeof useRecipeApplication>;
type Mutation = (name: string, args: Record<string, unknown>) => Promise<{ document?: Document; recipeId?: string } | null>;
const operation = (command: string) => ({ add_layer_filter: 'Append layer filter', update_adjustment: 'Set adjustment', update_text: 'Style existing text', set_layer_effects: 'Replace shadow / glow', set_layer_outline: 'Set outside outline' }[command] || command);
const valueText = (value: unknown) => value === null ? 'Clear / Auto' : typeof value === 'object' ? JSON.stringify(value) : String(value);
function RecipeSteps({ definition }: { definition: EditRecipeDefinition }) {
  return <ol className="recipe-steps" aria-label="Recipe step order">{definition.steps.map((step, index) => <li key={index}><strong>{index + 1}. {operation(step.command)} <span>→ {definition.slots.find(slot => slot.key === step.target)?.label || step.target}</span></strong><details><summary>Settings</summary><dl>{Object.entries(step.args).map(([key, value]) => <div key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd>{valueText(value)}</dd></div>)}</dl></details></li>)}</ol>;
}
function RecipeCapture({ document, layer, capabilities, busy, onSave }: { document: Document; layer?: Layer; capabilities: Backend; busy: boolean; onSave: (draft: EditRecipeDefinition, revision: number, overwrite: boolean) => Promise<void> }) {
  const [snapshot] = useState({ revision: document.revision, layer: layer ? structuredClone(layer) : undefined });
  const choices = captureChoices(snapshot.layer).filter(choice => capabilities.editRecipeCommands?.includes(choice.command));
  const [picked, setPicked] = useState(new Set(choices.filter(choice => choice.defaults).map(choice => choice.key))), [name, setName] = useState(''), [label, setLabel] = useState('Target layer');
  const blockedLookup = Boolean(picked.has('filters') && snapshot.layer?.filters?.some(filter => filter.kind === 'color_lookup') || picked.has('adjustment') && snapshot.layer?.kind === 'color_lookup');
  const blockedMask = Boolean(snapshot.layer?.filterMask && picked.has('filters'));
  const draft = snapshot.layer && !blockedMask && !blockedLookup ? captureRecipe(snapshot.layer, picked, name, label) : null, stale = snapshot.revision !== document.revision;
  const valid = Boolean(draft?.name && draft.steps.length && draft.steps.length <= (capabilities.limits?.maxEditRecipeSteps || 30) && label.trim() && !stale);
  return <section className="recipe-capture" aria-label="Capture layer settings"><p>Source: <strong>{snapshot.layer?.name || 'No selected layer'}</strong> · saved revision {snapshot.revision}. Captures persisted settings, including disabled filters; unapplied inspector drafts are excluded.</p>{snapshot.layer && effectiveLayerFill(snapshot.layer) !== 1 && <p className="recipe-notes">Layer Fill is not included; the target keeps its own Fill.</p>}{stale && <p role="alert">The source revision changed. Recapture current settings before saving.</p>}<label className="field-label">Recipe name<input aria-label="Captured recipe name" maxLength={200} value={name} onChange={event => setName(event.target.value)} disabled={busy} /></label><label className="field-label">Target slot label<input aria-label="Captured target label" maxLength={80} value={label} onChange={event => setLabel(event.target.value)} disabled={busy} /></label><div className="recipe-capture-choices">{choices.map(choice => <label key={choice.key}><input type="checkbox" aria-label={choice.label} checked={picked.has(choice.key)} disabled={busy || stale} onChange={event => setPicked(previous => { const next = new Set(previous); if (event.target.checked) { next.add(choice.key); const opposite = choice.key.startsWith('clear-') ? choice.key.slice(6) : `clear-${choice.key}`; next.delete(opposite); } else next.delete(choice.key); return next; })} />{choice.label}</label>)}</div>{!choices.length && <p>Choose a raster with filters, editable text, an adjustment or content with outside styles.</p>}{blockedLookup && <p className="recipe-error" role="alert">Recipes cannot carry Color Lookup files. Uncheck Filters to capture other available settings, or transfer the editable .prism project.</p>}{blockedMask && <p className="recipe-error" role="alert">Filter recipes cannot include this source effect mask. Uncheck Filters to capture other settings, or remove the mask explicitly before capturing filters.</p>}{snapshot.layer?.filterMask && !picked.has('filters') && <p className="recipe-notes">Filter entries and their source effect mask are excluded from this capture.</p>}{draft && <RecipeSteps definition={draft} />}<div className="recipe-actions"><button className="button secondary" disabled={busy || !valid || (document.editRecipes?.length || 0) >= (capabilities.limits?.maxEditRecipes || 16)} onClick={() => draft && void onSave(draft, snapshot.revision, false)}><Save size={13} />Save new recipe</button><button className="button subtle" disabled={busy || !valid || !document.editRecipes?.length} onClick={() => draft && void onSave(draft, snapshot.revision, true)}>Replace selected recipe</button></div><p>Typography keeps target text and position. Missing style choices leave those slots unchanged; explicit clear choices remove them. Saving does not apply edits.</p></section>;
}
export function EditRecipes({ document, layer, capabilities, busy, mutate, application, refresh }: { document: Document; layer?: Layer; capabilities: Backend; busy: boolean; mutate: Mutation; application: Application; refresh: () => Promise<void> }) {
  const recipes = document.editRecipes || [], [selectedId, setSelectedId] = useState(recipes[0]?.id || ''), selected = recipes.find(recipe => recipe.id === selectedId);
  const [view, setView] = useState<'library' | 'capture' | 'import'>('library'), [captureAttempt, setCaptureAttempt] = useState(0), [imported, setImported] = useState<EditRecipeDefinition | null>(null), [error, setError] = useState('');
  const [bindings, setBindings] = useState<Record<string, string>>({}), [inspection, setInspection] = useState<{ key: string; recipe: EditRecipe; recipeHash: string } | null>(null), [report, setReport] = useState<{ key: string; value: EditRecipeReport } | null>(null), [validating, setValidating] = useState(false);
  const [renameDraft, setRenameDraft] = useState({ key: '', value: '' });
  const fileInput = useRef<HTMLInputElement>(null), sequence = useRef(0), abortRef = useRef<AbortController | null>(null), alive = useRef(true);
  const boundLookup = selected?.steps.some(step => step.command === 'add_layer_filter' && document.layers.find(item => item.id === bindings[step.target])?.filters?.some(filter => filter.kind === 'color_lookup'));
  const spatialCapabilityKey = JSON.stringify([photoFilterCapabilityKey(capabilities), boundLookup ? colorLookupCapabilityKey(capabilities) : '', curvesCapabilityKey(capabilities), selectiveColorCapabilityKey(capabilities), targetedHSLCapabilityKey(capabilities), filterMaskCapabilityKey(capabilities), capabilities.id, capabilities.layerFilterCoordinates, capabilities.layerFilterSpatialPolicy, capabilities.layerFilterHighPassPolicy, capabilities.layerFilterUnsharpPolicy, capabilities.layerFilterNoisePolicy, capabilities.layerFilterLocalTonePolicy, capabilities.layerFilterBlendPolicy, capabilities.layerFilterBlendModes, capabilities.layerFilterKinds]);
  const context = `${document.backend}:${document.id}:${document.revision}:${selected?.id || ''}:${spatialCapabilityKey}`, latest = useRef(context); latest.current = context;
  const renaming = renameDraft.key === context ? renameDraft.value : selected?.name || '';
  const definition = inspection?.key === context ? inspection.recipe : selected, hash = inspection?.key === context ? inspection.recipeHash : '';
  const bindingKey = JSON.stringify((definition?.slots || []).map(slot => [slot.key, bindings[slot.key] || '']));
  const reportKey = `${context}:${hash}:${bindingKey}:${JSON.stringify([capabilities.editRecipeVersion, capabilities.editRecipeCommands, capabilities.editRecipeSlotTypes])}`, latestReport = useRef(reportKey); latestReport.current = reportKey;
  const currentReport = report?.key === reportKey ? report.value : null;
  const supported = Boolean(definition && !recipeHasLookup(definition) && definition.version === capabilities.editRecipeVersion && definition.steps.every(step => capabilities.editRecipeCommands?.includes(step.command) && (step.command !== 'update_adjustment' || definition.slots.find(slot => slot.key === step.target)?.kind !== 'curves' || supportsCurves(capabilities, document.backend, step.args.parameters, 'global') && supportsCurves(capabilities, document.backend, document.layers.find(layer => layer.id === bindings[step.target])?.parameters, 'global')) && (step.command !== 'update_adjustment' || definition.slots.find(slot => slot.key === step.target)?.kind !== 'selective_color' || supportsSelectiveColor(capabilities, document.backend, 'global')) && (step.command !== 'update_adjustment' || definition.slots.find(slot => slot.key === step.target)?.kind !== 'photo_filter' || supportsPhotoFilter(capabilities, document.backend, 'global')) && (step.command !== 'update_adjustment' || definition.slots.find(slot => slot.key === step.target)?.kind !== 'hue_saturation' || supportsTargetedHSL(capabilities, document.backend, 'global')) && (step.command !== 'add_layer_filter' || supportsSourceFilterEntry(capabilities, document.backend, step.args.kind, step.args.blendMode, step.args.parameters) && (document.layers.find(candidate => candidate.id === bindings[step.target])?.filters || []).every(filter => (filter.kind !== 'color_lookup' || supportsLookupEntry(capabilities, document.backend, 'source', filter.parameters)) && (filter.kind !== 'photo_filter' || supportsPhotoFilter(capabilities, document.backend, 'source'))) && (!document.layers.find(candidate => candidate.id === bindings[step.target])?.filterMask || supportsFilterMask(capabilities, document.backend) && supportsMask(document.layers.find(candidate => candidate.id === bindings[step.target])?.filterMask?.coverage, capabilities)))) && definition.slots.every(slot => capabilities.editRecipeSlotTypes?.includes(slot.type) && supportsMask(document.layers.find(layer => layer.id === bindings[slot.key])?.mask, capabilities)));
  const bindingValid = Boolean(definition && definition.slots.every(slot => { const candidate = document.layers.find(layer => layer.id === bindings[slot.key]); return candidate && slotMatches(slot, candidate); }) && new Set(definition.slots.map(slot => bindings[slot.key])).size === definition.slots.length);
  const can = (name: string) => capabilities.commands.includes(name);
  useEffect(() => { alive.current = true; return () => { alive.current = false; abortRef.current?.abort(); }; }, []);
  useEffect(() => { if (!recipes.some(recipe => recipe.id === selectedId)) { setSelectedId(recipes[0]?.id || ''); setBindings({}); } }, [document.revision, selectedId]);
  useEffect(() => {
    setReport(null); setError(''); setValidating(false); abortRef.current?.abort(); sequence.current++;
    if (!selected || !can('get_edit_recipe')) return;
    const controller = new AbortController();
    void command<{ documentId: string; revision: number; recipe: EditRecipe; recipeHash: string }>('native', 'get_edit_recipe', { documentId: document.id, expectedRevision: document.revision, recipeId: selected.id }, controller.signal).then(result => { if (!alive.current || controller.signal.aborted || latest.current !== context) return; if (result.documentId !== document.id || result.revision !== document.revision || result.recipe.id !== selected.id || !/^[0-9a-f]{64}$/.test(result.recipeHash)) throw Error('Recipe inspection changed. Refresh this document.'); setInspection({ key: context, recipe: result.recipe, recipeHash: result.recipeHash }); }).catch(error => { if (!controller.signal.aborted && alive.current && latest.current === context) setError(error.message); });
    return () => controller.abort();
  }, [context]);
  const validate = async () => {
    if (!definition || !hash || !bindingValid || busy || !supported) return;
    abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const attempt = ++sequence.current, key = reportKey, captured = Object.fromEntries(definition.slots.map(slot => [slot.key, bindings[slot.key]])); setValidating(true); setReport(null); setError('');
    try { const result = await command<EditRecipeReport>('native', 'validate_edit_recipe', { documentId: document.id, expectedRevision: document.revision, recipeId: definition.id, bindings: captured }, controller.signal); if (!alive.current || controller.signal.aborted || attempt !== sequence.current || latestReport.current !== key) return; if (result.documentId !== document.id || result.revision !== document.revision || result.recipeId !== definition.id || result.recipeHash !== hash || result.recipeVersion !== 1 || result.validation !== 'metadata-only' || result.stepCount !== definition.steps.length || Object.keys(result.bindings).length !== Object.keys(captured).length || Object.entries(captured).some(([slot, id]) => result.bindings[slot] !== id) || result.valid && (result.changes.length !== definition.steps.length || result.changes.some((change, index) => change.stepIndex !== index || change.target !== definition.steps[index].target || change.command !== definition.steps[index].command || change.layerId !== captured[change.target]))) throw Error('Validation did not match this recipe, revision and target mapping. Refresh and validate again.'); setReport({ key, value: result }); }
    catch (error) { if (!controller.signal.aborted && alive.current && latestReport.current === key) setError(error instanceof Error ? error.message : 'Validation failed.'); }
    finally { if (attempt === sequence.current) setValidating(false); }
  };
  const choose = (id: string) => { sequence.current++; abortRef.current?.abort(); setValidating(false); setSelectedId(id); setBindings({}); setReport(null); setError(''); };
  const changeBinding = (key: string, id: string) => { sequence.current++; abortRef.current?.abort(); setValidating(false); setBindings(previous => ({ ...previous, [key]: id })); setReport(null); setError(''); };
  const save = async (draft: EditRecipeDefinition, revision: number, overwrite: boolean) => {
    if (overwrite && !selected) return; setError('');
    try { const result = await mutate('save_edit_recipe', { documentId: document.id, expectedRevision: revision, name: draft.name, slots: draft.slots, steps: draft.steps, ...(overwrite ? { recipeId: selected!.id } : {}) }); if (result?.recipeId && alive.current) { choose(result.recipeId); setView('library'); setImported(null); } }
    catch (error) { if (alive.current) setError(error instanceof Error ? error.message : 'The recipe could not be saved.'); }
  };
  const libraryEdit = async (commandName: string, args: Record<string, unknown>) => { setError(''); try { await mutate(commandName, { documentId: document.id, expectedRevision: document.revision, ...args }); } catch (error) { if (alive.current) setError(error instanceof Error ? error.message : 'The library could not be updated.'); } };
  const importFile = async (file?: File) => { if (!file) return; setError(''); try { if (file.size > 65536) throw Error('Recipe transfer files must be at most 64 KiB.'); const draft = parseRecipeFile(await file.text()); if (!alive.current) return; setImported(draft); setView('import'); } catch (error) { if (alive.current) setError(error instanceof Error ? error.message : 'The recipe file could not be read.'); } };
  const recovery = application.pending;
  return <div className="edit-recipes"><span className="eyebrow">REPEAT A GOOD EDIT</span><h1 id="modal-title">Edit recipes</h1><p className="modal-intro">Reusable settings with explicit layer targets. This document’s library travels in its .prism project.</p><div className="recipe-view-tabs"><button className="button mini secondary" aria-pressed={view === 'library'} onClick={() => setView('library')}><Library size={13} />Library · {recipes.length}/{capabilities.limits?.maxEditRecipes || 16}</button><button className="button mini secondary" disabled={busy || !can('save_edit_recipe')} aria-pressed={view === 'capture'} onClick={() => { setCaptureAttempt(value => value + 1); setView('capture'); }}>Save selected layer settings</button><button className="button mini subtle" disabled={busy || !can('save_edit_recipe')} onClick={() => fileInput.current?.click()}><Upload size={13} />Import recipe</button><input ref={fileInput} aria-label="Import recipe definition file" type="file" accept=".json,.prism-recipe.json" hidden onChange={event => { void importFile(event.target.files?.[0]); event.target.value = ''; }} /></div><div className="recipe-scroll">
    {recovery && <section className="recipe-recovery" aria-label="Recipe application recovery"><strong>{application.working ? 'Confirming application…' : 'Application needs review'} · {recovery.name}</strong><p>{recovery.error || 'Keep this application identity until its outcome is confirmed.'}</p><p>Retry sends the same request ID, bindings and original revision. It never rebases or automatically appends again.</p><div className="recipe-actions"><button className="button secondary" disabled={busy || application.working} onClick={application.retry}>Retry same application</button><button className="button subtle" disabled={busy || application.working || !application.canInspect} onClick={() => void application.inspect()}>Inspect current document</button>{!application.canInspect && <p>Return to application document {recovery.args.documentId.slice(0, 8)} to inspect its outcome.</p>}{recovery.inspected && <button className="button subtle" disabled={busy || !application.canInspect} onClick={application.finishReview}>Finish outcome review</button>}</div></section>}
    {error && <p className="recipe-error" role="alert">{error}</p>}
    {view === 'capture' && <><button className="button mini subtle" disabled={busy} onClick={() => setCaptureAttempt(value => value + 1)}>Recapture current settings</button><RecipeCapture key={`${document.id}:${layer?.id}:${captureAttempt}`} document={document} layer={layer} capabilities={capabilities} busy={busy || !can('save_edit_recipe')} onSave={save} /></>}
    {view === 'import' && imported && <section aria-label="Imported recipe draft"><h2>{imported.name}</h2><p>Definition only · {imported.steps.length} {imported.steps.length === 1 ? 'step' : 'steps'}. Saving creates a new recipe ID; importing never applies edits.</p><RecipeSteps definition={imported} /><button className="button secondary" disabled={busy || !can('save_edit_recipe') || recipes.length >= (capabilities.limits?.maxEditRecipes || 16)} onClick={() => void save(imported, document.revision, false)}>Save imported recipe</button></section>}
    {view === 'library' && <>{recipes.length ? <label className="field-label">Recipe library<select aria-label="Saved edit recipe" value={selected?.id || ''} disabled={busy} onChange={event => choose(event.target.value)}>{recipes.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></label> : <p>No recipes saved. Capture selected-layer settings, import a definition, or ask your MCP assistant to save a typed recipe.</p>}{definition && <><div className="recipe-library-actions"><label className="field-label">Saved name<input aria-label="Saved recipe name" maxLength={200} value={renaming} disabled={busy} onChange={event => setRenameDraft({ key: context, value: event.target.value })} /></label><button className="button mini secondary" disabled={busy || !renaming.trim() || renaming.trim() === definition.name || !can('rename_edit_recipe')} onClick={() => void libraryEdit('rename_edit_recipe', { recipeId: definition.id, name: renaming.trim() })}>Rename recipe</button><button className="button mini subtle" disabled={busy || !can('delete_edit_recipe')} onClick={() => void libraryEdit('delete_edit_recipe', { recipeId: definition.id })}>Delete recipe</button><button className="button mini subtle" onClick={() => downloadBlob(new Blob([JSON.stringify({ format: 'prism-edit-recipe', version: definition.version, name: definition.name, slots: definition.slots, steps: definition.steps }, null, 2)], { type: 'application/json' }), `${definition.name.replace(/[^a-z0-9_-]/gi, '_').slice(0, 80) || 'recipe'}.prism-recipe.json`)}><Download size={13} />Export recipe</button></div><RecipeSteps definition={definition} />{!hash && can('get_edit_recipe') && <p role="status"><LoaderCircle size={12} className="spin" /> Reading canonical recipe…</p>}{!supported && <p className="recipe-error">This backend does not advertise every step, slot or required source-filter policy in this recipe. No steps will be skipped.</p>}
    <fieldset className="recipe-bindings" disabled={busy || Boolean(recovery)}><legend>Choose target layers</legend>{definition.slots.map(slot => <div key={slot.key}><label className="field-label">{slot.label || slot.key} · {slot.type}{slot.kind ? ` / ${slot.kind}` : ''}<select aria-label={`Recipe target ${slot.key}`} value={bindings[slot.key] || ''} onChange={event => changeBinding(slot.key, event.target.value)}><option value="">Choose a layer</option>{document.layers.map(candidate => { const used = definition.slots.some(other => other.key !== slot.key && bindings[other.key] === candidate.id); return <option key={candidate.id} value={candidate.id} disabled={!slotMatches(slot, candidate) || used}>{[...layerAncestors(document.layers, candidate).reverse().map(parent => parent.name), candidate.name].join(' / ')} · {candidate.type}{candidate.kind ? ` / ${candidate.kind}` : ''} · {candidate.id.slice(0, 6)}{used ? ' · already assigned' : candidate.protected ? ' · protected' : candidate.clipBaseId ? ' · clipped' : ''}</option>; })}</select></label>{document.layers.find(candidate => candidate.id === bindings[slot.key])?.filterMask && definition.steps.some(step => step.target === slot.key && step.command === 'add_layer_filter') && <p className="recipe-notes">New filters will use this target’s existing effect mask.</p>}<button className="button mini subtle" disabled={!layer || !slotMatches(slot, layer) || definition.slots.some(other => other.key !== slot.key && bindings[other.key] === layer.id)} onClick={() => layer && changeBinding(slot.key, layer.id)}>Use selected layer for {slot.label || slot.key}</button></div>)}</fieldset>
    <p className="recipe-notes">Filters append to existing stacks; applying again adds them again. Text and filters use source pixels, outside styles use canvas pixels. No proportional scaling. Selection is ignored; masks and protection remain.</p>
    {currentReport && <section className={`recipe-report ${currentReport.valid ? 'valid' : 'invalid'}`} aria-label="Recipe validation result">{currentReport.valid ? <strong>Ready at revision {currentReport.revision} · metadata checks passed</strong> : <strong>Recipe cannot be applied to these targets</strong>}{currentReport.issues.map((issue, index) => <p key={index}>{issue.stepIndex !== undefined ? `Step ${issue.stepIndex + 1} · ` : ''}{issue.target ? `${definition.slots.find(slot => slot.key === issue.target)?.label || issue.target} · ` : ''}{issue.message} <small>{issue.code}</small></p>)}{Boolean(currentReport.issuesOmitted) && <p>{currentReport.issuesOmitted} additional issues omitted.</p>}<p>Checks metadata and limits only. No pixel preview, source decoding or disk-space reservation.</p></section>}
    <div className="recipe-apply-actions"><button className="button secondary" disabled={busy || validating || !bindingValid || !supported || !hash || Boolean(recovery) || !can('validate_edit_recipe')} onClick={() => void validate()}>{validating ? <LoaderCircle size={14} className="spin" /> : <Check size={14} />}Validate recipe</button><button className="button primary" disabled={busy || validating || !supported || !bindingValid || !currentReport?.valid || Boolean(recovery) || !can('apply_edit_recipe')} onClick={() => { if (currentReport?.valid) { application.apply({ documentId: document.id, expectedRevision: currentReport.revision, recipeId: definition.id, bindings: Object.fromEntries(definition.slots.map(slot => [slot.key, bindings[slot.key]])) }, definition.name); setReport(null); } }}>Apply recipe · {definition.steps.length} {definition.steps.length === 1 ? 'step' : 'steps'}</button></div><p>Runs {definition.steps.length} {definition.steps.length === 1 ? 'step' : 'steps'} on {definition.slots.length} chosen {definition.slots.length === 1 ? 'layer' : 'layers'} as one undo step. Applied settings are independent of this library.</p></>}</>}
    </div><div className="recipe-footer"><button className="button subtle" disabled={busy || validating} onClick={() => { sequence.current++; abortRef.current?.abort(); setReport(null); setValidating(false); void refresh().catch(error => setError(error.message)); }}><RefreshCw size={13} />Refresh document and recipe</button><span>Saving, library edits and applying can be undone.</span></div></div>;
}
