import { supportsMask } from './dense-mask';
import { PhotoFilterControls } from './PhotoFilterControls';
import { photoFilterParameters, toPhotoFilterDraft, parsePhotoFilterDraft, supportsPhotoFilter, photoFilterCapabilityKey, type PhotoFilterDraft } from './photo-filter';
import { ColorLookup } from './ColorLookup';
import { colorLookupCapabilityKey, supportsColorLookup, supportsLookupEntry } from './color-lookup';
import { TargetedHSLControls } from './TargetedHSLControls';
import { targetedHSLParameters, toTargetedHSLDraft, parseTargetedHSLDraft, supportsTargetedHSL, targetedHSLCapabilityKey, type TargetedHSLDraft } from './targeted-hsl';
import { SelectiveColorControls } from './SelectiveColorControls';
import { selectiveColorParameters, toSelectiveColorDraft, parseSelectiveColorDraft, supportsSelectiveColor, selectiveColorCapabilityKey, isPreciseColorKind, type SelectiveColorDraft } from './selective-color';
import { curveParameters, toCurvesEditorDraft as toCurvesDraft, parseCurvesEditorDraft as parseCurvesDraft, isBankedCurves, supportsCurveBanks, supportsCurves, curvesCapabilityKey, curveCommandParameters, type CurvesEditorDraft as CurvesDraft } from './curves';
import { CurvesEditor, createCurvesInspection } from './CurvesEditor';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Check, Plus, RotateCcw, SlidersHorizontal, Trash2 } from 'lucide-react';
import type { AdjustmentParameters, LayerFilterParameters, Backend, CurvesParameters, Document, Layer, LevelsParameters } from './api';
import type { RunCommand } from './CanvasTools';
import { LEVELS_DEFAULT, LevelsControl, SCALAR_ADJUSTMENTS, validAdjustmentValue } from './ProPanels';
import './layer-filters.css';
import { ChannelMixerControl, GradientMapControl, MIXER_DEFAULT, GRADIENT_MAP_DEFAULT, mappingLabel, validColorMapping } from './ColorMappingControls';
import { TonalColorControl, isTonalKind, parseTonalDraft, toTonalDraft, tonalParameters, tonalValidationMessage, type TonalDraft } from './TonalColorControls';
import { captureGesture } from './gesture';
import { earlierProtectedFilterContent, filterStackActionHint, hasActiveLayerFilters, supportsFilterBake } from './filter-bake';
import { SOURCE_SPATIAL_DEFINITIONS, isSourceSpatialKind, parseSourceSigma, isPolicySourceKind, supportsPolicySourceKind } from './source-spatial-filters';
import { UnsharpMaskControls } from './UnsharpMaskControls';
import { parseUnsharpDraft, toUnsharpDraft, unsharpParameters, type UnsharpDraft } from './unsharp';
import { effectiveFilterBlend, filterBlendLabel, filterBlendModes, filterOpacityPercent, supportsFilterBlend } from './filter-blend';
import { HighPassGuidance } from './HighPassGuidance';
import { LocalToneControls } from './LocalToneControls';
import { localToneParameters, parseLocalToneDraft, toLocalToneDraft, type LocalToneDraft } from './local-tone';
import { NoiseControls } from './NoiseControls';
import { FilterMaskControls } from './FilterMaskControls';
import { filterMaskCapabilityKey, supportsFilterMask } from './filter-mask';
import { parseNoiseDraft, toNoiseDraft, noiseParameters, type NoiseDraft } from './noise';
const PARAMETERIZED = ['levels', 'curves', 'channel_mixer', 'gradient_map', 'color_balance', 'black_white', 'unsharp_mask', 'add_noise', 'shadows_highlights', 'selective_color', 'hue_saturation', 'color_lookup', 'photo_filter'];

const definitions = [...SCALAR_ADJUSTMENTS.filter(item => !isSourceSpatialKind(item.id)), ...SOURCE_SPATIAL_DEFINITIONS];
const label = (kind: string) => kind === 'color_lookup' ? 'Color Lookup' : kind === 'shadows_highlights' ? 'Local Shadows / Highlights' : kind === 'add_noise' ? 'Add Noise' : kind === 'unsharp_mask' ? 'Unsharp Mask' : definitions.find(item => item.id === kind)?.label || (kind === 'curves' ? 'Curves' : kind === 'levels' ? 'Levels' : mappingLabel(kind));
function filterParameters(kind: string, supplied?: AdjustmentParameters): AdjustmentParameters | undefined {
  // Choose a concrete complete default before merging validated persisted fields.
  // Saved projects may contain partial parameters even though command results are canonical.
  switch (kind) {
    case 'levels': return structuredClone({ ...LEVELS_DEFAULT, ...supplied });
    case 'curves': return curveParameters(supplied);
    case 'selective_color': return selectiveColorParameters(supplied);
    case 'photo_filter': return photoFilterParameters(supplied);
    case 'hue_saturation': return targetedHSLParameters(supplied);
    case 'channel_mixer': return structuredClone({ ...MIXER_DEFAULT, ...supplied });
    case 'gradient_map': return structuredClone({ ...GRADIENT_MAP_DEFAULT, ...supplied });
    case 'color_balance': case 'black_white': return tonalParameters(kind, supplied);
    default: return undefined;
  }
}
const storedParameters = (kind: string, supplied?: LayerFilterParameters) => kind === 'shadows_highlights' ? localToneParameters(supplied) : kind === 'add_noise' ? noiseParameters(supplied) : kind === 'unsharp_mask' ? unsharpParameters(supplied) : filterParameters(kind, supplied as AdjustmentParameters | undefined);
type FilterDraft = { photo?: PhotoFilterDraft; hsl?: TargetedHSLDraft; selective?: SelectiveColorDraft; curves?: CurvesDraft; value: number; sigma?: string; unsharp?: UnsharpDraft; noise?: NoiseDraft; localTone?: LocalToneDraft; parameters?: AdjustmentParameters; tonal?: TonalDraft; opacity: number; blendMode: string };
const initial = (kind: string): FilterDraft => ({ ...(kind === 'photo_filter' ? { photo: toPhotoFilterDraft() } : {}), ...(kind === 'hue_saturation' ? { hsl: toTargetedHSLDraft() } : {}), ...(kind === 'selective_color' ? { selective: toSelectiveColorDraft() } : {}), ...(kind === 'curves' ? { curves: toCurvesDraft() } : {}), value: definitions.find(item => item.id === kind)?.initial ?? (kind === 'exposure' ? 0.5 : PARAMETERIZED.includes(kind) ? 0 : 15), ...(isSourceSpatialKind(kind) ? { sigma: String(SOURCE_SPATIAL_DEFINITIONS.find(item => item.id === kind)!.initial) } : {}), ...(kind === 'shadows_highlights' ? { localTone: toLocalToneDraft() } : {}), ...(kind === 'add_noise' ? { noise: toNoiseDraft() } : {}), ...(kind === 'unsharp_mask' ? { unsharp: toUnsharpDraft() } : {}), ...(isTonalKind(kind) ? { tonal: toTonalDraft(kind) } : { parameters: filterParameters(kind) }), opacity: 1, blendMode: 'normal' });
function validParameters(kind: string, parameters?: AdjustmentParameters) {
  if (kind === 'channel_mixer' || kind === 'gradient_map') return validColorMapping(kind, parameters);
  if (kind === 'levels') {
    const p = parameters as LevelsParameters;
    return p && [p.black, p.white, p.gamma, p.outputBlack, p.outputWhite].every(Number.isFinite) && p.black >= 0 && p.black <= 254 && p.white >= 1 && p.white <= 255 && p.black < p.white && p.gamma >= .1 && p.gamma <= 10 && p.outputBlack >= 0 && p.outputWhite <= 255 && p.outputBlack <= p.outputWhite;
  }
  if (kind === 'curves') {
    return Boolean(parseCurvesDraft(toCurvesDraft(parameters)));
  }
  return true;
}

export function LayerFilters({ document, layer, capabilities, busy, can, run, onInspectFilterMask }: { document: Document; layer: Layer; capabilities: Backend; busy: boolean; can: (name: string) => boolean; run: RunCommand; onInspectFilterMask?: () => void }) {
  const filters = layer.filters || [];
  const maskSupported = !layer.filterMask || supportsFilterMask(capabilities, document.backend) && supportsMask(layer.filterMask.coverage, capabilities) && (layer.filterMask.coverage.shape !== 'alpha8' || capabilities.layerFilterMaskShapes?.includes('alpha8'));
  const kinds = (capabilities.layerFilterKinds || []).filter(kind => (definitions.some(item => item.id === kind) || PARAMETERIZED.includes(kind)) && (!isPolicySourceKind(kind) || supportsPolicySourceKind(capabilities, document.backend, kind)));
  const [lookupReview, setLookupReview] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(filters[0]?.id || null);
  const [newKind, setNewKind] = useState(kinds[0] || 'exposure');
  const selected = filters.find(filter => filter.id === selectedId);
  const kind = selected?.kind || newKind;
  const capabilityKey = JSON.stringify([photoFilterCapabilityKey(capabilities), colorLookupCapabilityKey(capabilities), curvesCapabilityKey(capabilities), selectiveColorCapabilityKey(capabilities), targetedHSLCapabilityKey(capabilities), filterMaskCapabilityKey(capabilities), capabilities.commands, kinds, capabilities.layerFilterCoordinates, capabilities.layerFilterSpatialPolicy, capabilities.layerFilterHighPassPolicy, capabilities.layerFilterUnsharpPolicy, capabilities.layerFilterNoisePolicy, capabilities.layerFilterLocalTonePolicy, capabilities.layerFilterBlendPolicy, capabilities.layerFilterBlendModes, capabilities.limits?.maxFiltersPerLayer, capabilities.limits?.maxFiltersPerDocument, capabilities.layerFilterBaking, capabilities.limits?.maxFilterBakeWorkingBytes, capabilities.limits?.maxFilterBakeAssetBytes]);
  const targetIdentity = `${document.backend}:${document.id}:${layer.id}:${selected?.id || 'new'}:${kind}`;
  const curveInspection = useRef({ targetIdentity, value: createCurvesInspection() });
  if (curveInspection.current.targetIdentity !== targetIdentity) curveInspection.current = { targetIdentity, value: createCurvesInspection() };
  const identityKey = `${targetIdentity}:${capabilities.id}:${capabilityKey}`;
  const latestIdentity = useRef(identityKey); latestIdentity.current = identityKey;
  const execution = useRef({ key: identityKey, epoch: 0 }); if (execution.current.key !== identityKey) execution.current = { key: identityKey, epoch: execution.current.epoch + 1 }; const executionEpoch = execution.current.epoch;
  const [curveDragging, setCurveDragging] = useState(false);
  const alive = useRef(true); useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const stackIdentityKey = `${document.backend}:${document.id}:${layer.id}:${capabilities.id}:${capabilityKey}`;
  const latestStackIdentity = useRef(stackIdentityKey); latestStackIdentity.current = stackIdentityKey;
  const stackExecution = useRef({ key: stackIdentityKey, epoch: 0 }); if (stackExecution.current.key !== stackIdentityKey) stackExecution.current = { key: stackIdentityKey, epoch: stackExecution.current.epoch + 1 }; const stackEpoch = stackExecution.current.epoch;
  const draftKey = `${targetIdentity}:${document.revision}`;
  const storedDraft = (): FilterDraft => selected ? { ...(selected.kind === 'photo_filter' ? { photo: toPhotoFilterDraft(selected.parameters) } : {}), ...(selected.kind === 'hue_saturation' ? { hsl: toTargetedHSLDraft(selected.parameters) } : {}), ...(selected.kind === 'selective_color' ? { selective: toSelectiveColorDraft(selected.parameters) } : {}), ...(selected.kind === 'curves' ? { curves: toCurvesDraft(selected.parameters) } : {}), value: selected.value, ...(isSourceSpatialKind(selected.kind) ? { sigma: String(selected.value) } : {}), ...(selected.kind === 'shadows_highlights' ? { localTone: toLocalToneDraft(selected.parameters) } : selected.kind === 'add_noise' ? { noise: toNoiseDraft(selected.parameters) } : selected.kind === 'unsharp_mask' ? { unsharp: toUnsharpDraft(selected.parameters) } : isTonalKind(selected.kind) ? { tonal: toTonalDraft(selected.kind, selected.parameters as AdjustmentParameters) } : { parameters: filterParameters(selected.kind, selected.parameters as AdjustmentParameters) }), opacity: selected.opacity, blendMode: effectiveFilterBlend(selected.blendMode) } : initial(kind);
  const [draftState, setDraftState] = useState<{ key: string; value: FilterDraft }>(() => ({ key: draftKey, value: storedDraft() }));
  // A newly selected filter must expose its own settings in the first render.
  // Waiting for an effect leaves a window where controls can edit the previous filter's draft.
  const draft = draftState.key === draftKey ? draftState.value : storedDraft();
  if (draftState.key !== draftKey) setDraftState({ key: draftKey, value: draft });
  const setDraft = (value: FilterDraft) => setDraftState({ key: draftKey, value });
  const definition = definitions.find(item => item.id === kind);
  const spatial = isSourceSpatialKind(kind);
  const unsharp = kind === 'unsharp_mask', noise = kind === 'add_noise', localTone = kind === 'shadows_highlights';
  const value = unsharp || noise || localTone ? 0 : spatial ? parseSourceSigma(kind, draft.sigma) : draft.value;
  const parameters = kind === 'photo_filter' ? parsePhotoFilterDraft(draft.photo) : kind === 'hue_saturation' ? parseTargetedHSLDraft(draft.hsl) : kind === 'selective_color' ? parseSelectiveColorDraft(draft.selective) : kind === 'curves' ? parseCurvesDraft(draft.curves) : localTone ? parseLocalToneDraft(draft.localTone) : noise ? parseNoiseDraft(draft.noise) : unsharp ? parseUnsharpDraft(draft.unsharp) : isTonalKind(kind) ? parseTonalDraft(draft.tonal) : draft.parameters;
  const modes = filterBlendModes(capabilities, document.backend, kind);
  const savedBlendSupported = !selected || supportsFilterBlend(capabilities, document.backend, kind, selected.blendMode);
  const draftBlendSupported = modes.includes(draft.blendMode);
  const unsupportedStackBlend = filters.some(filter => effectiveFilterBlend(filter.blendMode) !== 'normal' && !supportsFilterBlend(capabilities, document.backend, filter.kind, filter.blendMode));
  const savedLookupSupported = !selected || kind !== 'color_lookup' || supportsLookupEntry(capabilities, document.backend, 'source', selected.parameters);
  const savedCurveSupported = !selected || kind !== 'curves' || supportsCurves(capabilities, document.backend, selected.parameters, 'source');
  const bankedDraftSupported = kind !== 'curves' || draft.curves?.mode !== 'banks' || supportsCurves(capabilities, document.backend, draft.curves, 'source');
  const unsupportedStackCurves = filters.some(filter => filter.kind === 'curves' && !supportsCurves(capabilities, document.backend, filter.parameters, 'source'));
  const unsupportedStackPhoto = filters.some(filter => filter.kind === 'photo_filter' && !supportsPhotoFilter(capabilities, document.backend, 'source'));
  const unsupportedStackHSL = filters.some(filter => filter.kind === 'hue_saturation' && !supportsTargetedHSL(capabilities, document.backend, 'source'));
  const unsupportedStackLookup = filters.some(filter => filter.kind === 'color_lookup' && !supportsLookupEntry(capabilities, document.backend, 'source', filter.parameters));
  const unsupportedStackSelective = filters.some(filter => filter.kind === 'selective_color' && !supportsSelectiveColor(capabilities, document.backend, 'source'));
  const valid = !curveDragging && savedLookupSupported && savedCurveSupported && (kind !== 'curves' || Boolean(parameters) && supportsCurves(capabilities, document.backend, parameters, 'source')) && maskSupported && kinds.includes(kind) && savedBlendSupported && draftBlendSupported && (kind === 'photo_filter' || kind === 'hue_saturation' || kind === 'selective_color' || unsharp || noise || localTone ? Boolean(parameters) : spatial ? value !== undefined : isTonalKind(kind) ? Boolean(parameters) : kind === 'curves' ? Boolean(parameters) : definition ? validAdjustmentValue(definition, draft.value) : validParameters(kind, draft.parameters)) && Number.isFinite(draft.opacity) && draft.opacity >= 0 && draft.opacity <= 1;
  const frozen = busy || Boolean(layer.protected) || lookupReview;
  const total = document.layers.reduce((count, item) => count + (item.filters?.length || 0), 0);
  const atLimit = filters.length >= (capabilities.limits?.maxFiltersPerLayer || 8) || total >= (capabilities.limits?.maxFiltersPerDocument || 64);
  const dirty = Boolean(selected && (draft.blendMode !== effectiveFilterBlend(selected.blendMode) || value !== selected.value || draft.opacity !== selected.opacity || JSON.stringify(parameters) !== JSON.stringify(storedParameters(selected.kind, selected.parameters))));
  const bakingSupported = document.backend === 'native' && supportsFilterBake(capabilities);
  const active = hasActiveLayerFilters(layer);
  const protectedPrefix = earlierProtectedFilterContent(document, layer);
  const captureStackContext = () => ({ ...captureGesture(document, layer.id), isCurrent: () => alive.current && latestStackIdentity.current === stackIdentityKey && stackExecution.current.epoch === stackEpoch });
  const finalize = (bake: boolean) => {
    if (frozen || !filters.length || document.backend !== capabilities.id || (bake ? !bakingSupported || Boolean(protectedPrefix) : !can('clear_layer_filters'))) return;
    void run(bake ? 'bake_layer_filters' : 'clear_layer_filters', { layerId: layer.id }, bake ? 'Baking layer filters' : 'Clearing layer filters', captureStackContext());
  };
  const captureContext = (actionKind = kind) => ({ ...captureGesture(document, layer.id), ...(isPreciseColorKind(actionKind) || actionKind === 'color_lookup' ? { preciseColor: {} } : {}), isCurrent: () => alive.current && latestIdentity.current === identityKey && execution.current.epoch === executionEpoch });
  const apply = async () => {
    if (!selected && kind === 'color_lookup') return;
    if (frozen || !maskSupported || !valid || (selected ? !dirty || !can('update_layer_filter') : atLimit || !can('add_layer_filter'))) return;
    const context = captureContext();
    const result = await run(selected ? 'update_layer_filter' : 'add_layer_filter', { layerId: layer.id, ...(selected ? { filterId: selected.id } : { kind }), value, ...(PARAMETERIZED.includes(kind) && parameters ? { parameters: kind === 'curves' ? curveCommandParameters(parameters as CurvesParameters, selected?.parameters) : parameters } : {}), opacity: draft.opacity, ...(draft.blendMode !== 'normal' || selected && effectiveFilterBlend(selected.blendMode) !== 'normal' ? { blendMode: draft.blendMode } : {}) }, selected ? 'Updating layer filter' : 'Adding layer filter', context);
    if (result?.document && !selected && context.isCurrent()) {
      const added = result.document.layers.find(item => item.id === layer.id)?.filters?.find(filter => !filters.some(existing => existing.id === filter.id));
      if (added) setSelectedId(added.id);
    }
  };
  if (layer.type !== 'raster') return <section className="panel-section layer-filters" aria-label="Layer filters"><div className="section-heading"><span>Layer filters</span><SlidersHorizontal size={14} /></div><p className="property-hint">Choose a raster image layer for editable filters.{!['group', 'adjustment'].includes(layer.type) && ' Rasterize this layer explicitly to use pixel filters.'}</p></section>;
  return <section className="panel-section layer-filters" aria-label="Layer filters">
    <div className="section-heading"><span>Layer filters</span><span className="count-badge">{filters.length}/{capabilities.limits?.maxFiltersPerLayer || 8}</span><SlidersHorizontal size={14} /></div>
    <p className="property-hint">Runs from 1 downward on source pixels, before transforms. Median/mosaic sizes and spatial sigma scale with the layer. Capture selections explicitly in Filter effect mask. The layer mask controls visibility.</p>
    {layer.protected && <p className="filter-warning">Original pixels are protected. Unprotect explicitly to edit this stack.</p>}
    {filters.length > 0 && <ol className="filter-stack" aria-label="Filter execution order">{filters.map((filter, index) => <li key={filter.id} data-filter-id={filter.id} className={selected?.id === filter.id ? 'selected' : ''}>
      <label className="filter-enabled"><input type="checkbox" aria-label={`Enable filter ${index + 1} ${label(filter.kind)}`} checked={filter.enabled} disabled={frozen || !maskSupported || filter.kind === 'color_lookup' && !supportsLookupEntry(capabilities, document.backend, 'source', filter.parameters) || !can('update_layer_filter') || !kinds.includes(filter.kind) || !supportsFilterBlend(capabilities, document.backend, filter.kind, filter.blendMode) || filter.kind === 'curves' && !supportsCurves(capabilities, document.backend, filter.parameters, 'source')} onChange={event => void run('update_layer_filter', { layerId: layer.id, filterId: filter.id, enabled: event.target.checked }, 'Toggling layer filter', captureContext(filter.kind))} /></label>
      <button className="filter-select" aria-label={`Edit filter ${index + 1} ${label(filter.kind)}`} onClick={() => setSelectedId(filter.id)}><span>{index + 1}. {label(filter.kind)}</span><small>{effectiveFilterBlend(filter.blendMode) !== 'normal' && `${filterBlendLabel(effectiveFilterBlend(filter.blendMode))} · `}{filter.enabled ? `${filterOpacityPercent(filter.opacity)}%` : 'Disabled'}</small></button>
      <div className="filter-order"><button className="icon-button" aria-label={`Move filter ${index + 1} earlier`} disabled={frozen || !maskSupported || unsupportedStackLookup || unsupportedStackPhoto || unsupportedStackBlend || unsupportedStackCurves || unsupportedStackSelective || unsupportedStackHSL || index === 0 || !can('reorder_layer_filter')} onClick={() => void run('reorder_layer_filter', { layerId: layer.id, filterId: filter.id, index: index - 1 }, 'Reordering layer filters', captureStackContext())}><ArrowUp size={12} /></button><button className="icon-button" aria-label={`Move filter ${index + 1} later`} disabled={frozen || !maskSupported || unsupportedStackLookup || unsupportedStackPhoto || unsupportedStackBlend || unsupportedStackCurves || unsupportedStackSelective || unsupportedStackHSL || index === filters.length - 1 || !can('reorder_layer_filter')} onClick={() => void run('reorder_layer_filter', { layerId: layer.id, filterId: filter.id, index: index + 1 }, 'Reordering layer filters', captureStackContext())}><ArrowDown size={12} /></button><button className="icon-button" aria-label={`Delete filter ${index + 1} ${label(filter.kind)}`} title={layer.filterMask && filters.length === 1 ? 'Deleting the final filter also removes its effect mask. Undo restores both.' : undefined} disabled={frozen || !can('delete_layer_filter') || filters.length > 1 && !maskSupported} onClick={() => void run('delete_layer_filter', { layerId: layer.id, filterId: filter.id }, 'Deleting layer filter', captureStackContext())}><Trash2 size={12} /></button></div>
    </li>)}</ol>}
    {!maskSupported && <p className="filter-mask-unavailable">This companion does not advertise the saved filter effect-mask policy. Filter edits and reordering are unavailable; supported removal actions remain available.</p>}
    <FilterMaskControls document={document} layer={layer} capabilities={capabilities} busy={busy} run={run} captureContext={captureStackContext} onInspect={onInspectFilterMask} />
    {unsupportedStackLookup && <p className="tonal-unavailable">This companion does not advertise the saved Color Lookup policy. Its metadata remains available; editing, enabling and stack reordering are unavailable.</p>}
    {unsupportedStackPhoto && <p className="tonal-unavailable">This companion does not advertise the saved Photo Filter policy. Editing, enabling and stack reordering are unavailable; supported removal actions remain available.</p>}
    {unsupportedStackHSL && <p className="tonal-unavailable">This companion does not advertise the complete saved Hue / Saturation policy. Editing, enabling and stack reordering are unavailable; supported removal actions remain available.</p>}
    {unsupportedStackSelective && <p className="tonal-unavailable">This companion does not advertise the complete saved Selective Color policy. Editing, enabling and stack reordering are unavailable; supported removal actions remain available.</p>}
    {unsupportedStackCurves && <p className="tonal-unavailable">This companion does not advertise a saved {filters.some(filter => filter.kind === 'curves' && isBankedCurves(filter.parameters) && !supportsCurves(capabilities, document.backend, filter.parameters, 'source')) ? 'curve bank or its Smooth interpolation' : 'Smooth curve'}. Editing, enabling and stack reordering are unavailable; supported removal actions remain available.</p>}
    {unsupportedStackBlend && <p className="filter-blend-unavailable">This companion does not advertise a saved filter blend. Stack reordering is unavailable; review the entry or use the supported removal actions.</p>}
    {filters.length > 0 && <section className="filter-finalize" aria-label="Bake or clear saved filters">
      <p>{!active ? bakingSupported ? 'Every filter is disabled or at 0% opacity. Bake and Clear both remove these entries without changing pixels; no image is evaluated.' : 'Every filter is disabled or at 0% opacity. Clear removes these entries without changing pixels.' : bakingSupported ? layer.filterMask ? 'Bake fixes the current masked filter result into pixels and removes the editable filters and their effect mask. Clear removes both and their effect. Undo restores them.' : 'Bake keeps the current filter result as pixels and removes editable filter entries. Clear removes the entries and their effect. Undo restores the stack.' : layer.filterMask ? 'Clear removes the editable filter entries and their effect mask. Undo restores both.' : 'Clear removes the editable filter entries and their effect. Undo restores the stack.'}</p>
      <p className="property-hint">{layer.filterMask && !active && 'The effect mask is removed too. '}Uses the saved stack above. Apply a pending draft first to include it.</p>
      <div className="filter-finalize-actions">{bakingSupported && <button className="button mini secondary" disabled={frozen || Boolean(protectedPrefix)} onClick={() => finalize(true)}>Bake filters</button>}<button className="button mini subtle" disabled={frozen || !can('clear_layer_filters')} onClick={() => finalize(false)}>Clear filters</button></div>
      {!bakingSupported && <p className="property-hint">This companion does not advertise source-space filter baking.</p>}
      {bakingSupported && protectedPrefix && <p className="filter-warning">Baking is unavailable while earlier content “{protectedPrefix.name}” is protected. Keep the editable filters, or review layer order and protection explicitly.</p>}
      {bakingSupported && active && <p className="filter-bake-disclosure">Original image, geometry, source alpha and the additional layer mask are kept. Baking fixes filter colors in the working image. Pixels hidden by source alpha stay ungraded if you reveal them later; spatial filters keep their current cutout-edge sampling.</p>}
    </section>}
    <div className="filter-compose-actions"><button className="button mini subtle" aria-pressed={!selected} disabled={frozen || !maskSupported || atLimit || !(can('add_layer_filter') || can('import_color_lookup') && supportsColorLookup(capabilities, document.backend, 'source'))} onClick={() => { setSelectedId(null); setDraft(initial(newKind)); }}><Plus size={12} />New filter</button></div>
    <fieldset disabled={kind !== 'color_lookup' && kind !== 'selective_color' && kind !== 'hue_saturation' && !(kind === 'curves' && draft.curves?.mode === 'banks') && (frozen || !maskSupported || Boolean(selected && (!isPreciseColorKind(kind) && !kinds.includes(kind) || !savedBlendSupported)))} className="filter-editor" aria-label={selected ? `Editing ${label(kind)} filter` : 'New layer filter'}>
      {selected ? <strong className="filter-editor-title">Edit {label(kind)}</strong> : <label className="field-label">Filter<select disabled={frozen || !maskSupported} aria-label="New layer filter kind" value={newKind} onChange={event => { setNewKind(event.target.value); setDraft(initial(event.target.value)); }}>{!kinds.includes(newKind) && <option value={newKind} disabled>{label(newKind)} · unavailable</option>}{kinds.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label>}
      {definition && !spatial && <><label className="field-label">{definition.label}{['median', 'mosaic'].includes(kind) ? ', source pixels' : definition.unit ? `, ${definition.unit.trim()}` : ''}<input aria-label="Layer filter value" type="number" min={definition.min} max={definition.max} step={definition.step} value={draft.value} onChange={event => setDraft({ ...draft, value: Number(event.target.value) })} /></label><input aria-label="Layer filter amount" type="range" min={definition.min} max={definition.max} step={definition.step} value={draft.value} onChange={event => setDraft({ ...draft, value: Number(event.target.value) })} /></>}
      {spatial && definition && <><label className="field-label">Sigma, source px<input aria-label="Layer filter value" disabled={!kinds.includes(kind)} type="number" min="0" max={definition.max} step="any" value={draft.sigma ?? ''} onChange={event => setDraft({ ...draft, sigma: event.target.value })} /></label><input aria-label="Layer filter amount" disabled={!kinds.includes(kind)} type="range" min="0" max={definition.max} step="0.1" value={value ?? 0} onChange={event => setDraft({ ...draft, sigma: event.target.value })} />{kind === 'high_pass' ? <HighPassGuidance sigma={value} /> : <div className="spatial-filter-guidance"><p>Changes RGB on source pixels before transforms. Alpha and the cutout silhouette stay unchanged; masks and layer opacity apply afterward.</p><p>{kind === 'blur' ? 'Blends neighboring visible colors. Sigma 0 adds no blur; tiny values may add no blur. Filter blending may still change colors.' : 'RGB unsharp with fixed amount 1 and threshold 0. Sigma sets the neighborhood; filter opacity blends its result. This is separate from the global Sharpen adjustment.'}</p>{kind === 'sharpen' && <p>Sigma 0 adds no sharpening; tiny values may add none. Filter blending may still change colors.</p>}<p>Larger sigma values and source images use more work. A limit refusal keeps the existing stack unchanged.</p>{value === 0 && <p className="spatial-identity-note">{draft.blendMode === 'normal' ? 'Zero leaves pixels unchanged in Normal mode.' : 'Zero adds no blur or sharpening. Filter blending can still change colors.'} After saving, this filter remains in the stack; Bake or Clear removes it before source editing.</p>}</div>}</>}
      {unsharp && draft.unsharp && <><UnsharpMaskControls blendMode={draft.blendMode} draft={draft.unsharp} disabled={!kinds.includes(kind)} onChange={unsharp => setDraft({ ...draft, unsharp })} /><button className="button mini subtle tonal-local-reset" type="button" aria-label="Reset Unsharp Mask" disabled={!kinds.includes(kind)} onClick={() => setDraft({ ...draft, unsharp: toUnsharpDraft() })}><RotateCcw size={11} />Reset Unsharp Mask</button></>}
      {localTone && draft.localTone && <><LocalToneControls blendMode={draft.blendMode} draft={draft.localTone} disabled={!kinds.includes(kind)} onChange={localTone => setDraft({ ...draft, localTone })} /><button className="button mini subtle tonal-local-reset" type="button" aria-label="Reset Local Shadows / Highlights" disabled={!kinds.includes(kind)} onClick={() => setDraft({ ...draft, localTone: toLocalToneDraft() })}><RotateCcw size={11} />Reset Local Shadows / Highlights</button></>}
      {noise && draft.noise && <><NoiseControls blendMode={draft.blendMode} draft={draft.noise} disabled={!kinds.includes(kind)} onChange={noise => setDraft({ ...draft, noise })} /><button className="button mini subtle tonal-local-reset" type="button" aria-label="Reset Add Noise" disabled={!kinds.includes(kind)} onClick={() => setDraft({ ...draft, noise: toNoiseDraft() })}><RotateCcw size={11} />Reset Add Noise</button></>}
      {kind === 'photo_filter' && <PhotoFilterControls key={draftKey} source draft={draft.photo ?? toPhotoFilterDraft()} blendMode={draft.blendMode} onChange={photo => setDraft({ ...draft, photo })} disabled={frozen || !maskSupported || !kinds.includes(kind) || !savedBlendSupported} />}
      {kind === 'hue_saturation' && <TargetedHSLControls key={draftKey} source draft={draft.hsl ?? toTargetedHSLDraft()} blendMode={draft.blendMode} onChange={hsl => setDraft({ ...draft, hsl })} disabled={frozen || !maskSupported || !kinds.includes(kind) || !savedBlendSupported} />}
      {kind === 'selective_color' && <SelectiveColorControls key={draftKey} source draft={draft.selective ?? toSelectiveColorDraft()} blendMode={draft.blendMode} onChange={selective => setDraft({ ...draft, selective })} disabled={frozen || !maskSupported || !kinds.includes(kind) || !savedBlendSupported} />}
      {kind === 'levels' && <LevelsControl value={draft.parameters && 'black' in draft.parameters ? draft.parameters : LEVELS_DEFAULT} onChange={parameters => setDraft({ ...draft, parameters })} />}
      {kind === 'curves' && <CurvesEditor draft={draft.curves ?? toCurvesDraft()} inspection={curveInspection.current.value} bankSupported={supportsCurveBanks(capabilities, document.backend, 'source')} histogram={null} onChange={curves => setDraft({ ...draft, curves })} disabled={frozen || !maskSupported || !savedCurveSupported || !bankedDraftSupported || !kinds.includes(kind) || !savedBlendSupported} smoothSupported={supportsCurves(capabilities, document.backend, { interpolation: 'smooth' }, 'source')} contextKey={`${draftKey}:${capabilityKey}`} sessionKey={draftKey} onDragging={setCurveDragging} />}
      {kind === 'channel_mixer' && <ChannelMixerControl value={draft.parameters && 'monochrome' in draft.parameters ? draft.parameters : MIXER_DEFAULT} onChange={parameters => setDraft({ ...draft, parameters })} />}
      {kind === 'gradient_map' && <GradientMapControl value={draft.parameters && 'stops' in draft.parameters ? draft.parameters : GRADIENT_MAP_DEFAULT} onChange={parameters => setDraft({ ...draft, parameters })} />}
      {isTonalKind(kind) && draft.tonal && <><TonalColorControl key={draftKey} draft={draft.tonal} onChange={tonal => setDraft({ ...draft, tonal })} /><button className="button mini subtle tonal-local-reset" type="button" aria-label={`Reset ${label(kind)}`} onClick={() => setDraft({ ...draft, tonal: toTonalDraft(kind) })}><RotateCcw size={11} />Reset {label(kind)}</button></>}
      {kind === 'color_lookup' && <ColorLookup key={`${document.backend}:${document.id}:${layer.id}:${selected?.id || 'new'}`} document={document} capabilities={capabilities} scope="source" layer={layer} filter={selected} busy={busy} blocked={!maskSupported || !savedBlendSupported || (!selected && atLimit)} settingsDirty={dirty} supportKey={capabilityKey} run={run} onReviewChange={setLookupReview} onImported={setSelectedId} />}
      {(kind !== 'color_lookup' || selected) && <>
      <div className="filter-blend-controls"><label className="field-label">Filter blend<select aria-label="Layer filter blend mode" disabled={frozen || !maskSupported || !savedBlendSupported || !kinds.includes(kind) || !savedCurveSupported || !bankedDraftSupported} value={draft.blendMode} onChange={event => setDraft({ ...draft, blendMode: event.target.value })}>{!modes.includes(draft.blendMode) && <option value={draft.blendMode} disabled>{filterBlendLabel(draft.blendMode)} · unavailable</option>}{modes.map(mode => <option key={mode} value={mode}>{filterBlendLabel(mode)}</option>)}</select></label><p className="property-hint">Blends this filter with its input RGB, before layer blending.</p><details className="filter-blend-help"><summary>How filter blending works</summary><p>The filter runs on source pixels after earlier entries. Its result blends with the pixels it received, then filter opacity fades that blend.</p><p>Alpha stays exact; fully transparent RGB stays ungraded. Layer opacity, masks and layer blending apply later.</p><p>A zero filter amount can still change colors in modes such as Multiply or Screen. Disable the entry or set filter opacity to 0 to bypass it.</p></details></div>
      <label className="field-label">Filter opacity, %<input aria-label="Layer filter opacity" disabled={frozen || !maskSupported || !savedBlendSupported || !savedLookupSupported || !savedCurveSupported || !bankedDraftSupported || !kinds.includes(kind)} type="number" min="0" max="100" step="any" value={filterOpacityPercent(draft.opacity)} onChange={event => setDraft({ ...draft, opacity: Number(event.target.value) / 100 })} /></label>
      {kind === 'color_lookup' && selected && <button className="button mini subtle" disabled={frozen || !savedLookupSupported || !dirty} onClick={() => setDraft(storedDraft())}>Reset filter settings</button>}
      <button className="button secondary wide" disabled={frozen || !valid || (selected ? !dirty || !can('update_layer_filter') : atLimit || !can('add_layer_filter'))} onClick={() => void apply()}>{selected ? <Check size={12} /> : <Plus size={12} />}{selected ? 'Apply filter changes' : 'Add layer filter'}</button>
      </>}
    </fieldset>
    {!kinds.includes(kind) && <p className="tonal-unavailable">{isPolicySourceKind(kind) ? `This companion does not advertise ${label(kind)} with the required source-pixel RGB policy. Its saved settings remain unchanged.` : `This companion does not advertise ${label(kind)}. Its saved settings remain unchanged.`}</p>}
    {(!savedBlendSupported || !draftBlendSupported) && <p className="filter-blend-unavailable">{!savedBlendSupported ? `This companion does not advertise the saved ${filterBlendLabel(effectiveFilterBlend(selected?.blendMode))} filter blend. Its settings remain unchanged.` : `This companion does not advertise the draft ${filterBlendLabel(draft.blendMode)} filter blend. Choose a supported mode to apply; the draft is retained.`}</p>}
    {!valid && maskSupported && kinds.includes(kind) && savedBlendSupported && draftBlendSupported && <p className="inline-panel-error">{kind === 'photo_filter' ? 'Use a six-digit #rrggbb color and Density 0–100% in exact 0.01% increments.' : kind === 'hue_saturation' ? 'Complete every range using Hue −180 to 180°, Saturation and Lightness −100 to 100%, in exact 0.01 increments.' : kind === 'selective_color' ? 'Complete every range using −100 to 100% in exact 0.01% increments.' : localTone ? 'Use Amounts 0–100% and Tonal widths 1–100% in exact 0.01% increments, finite Sigma 0–50 source px, and opacity 0–100%.' : noise ? 'Use Amount 0–400% in exact 0.01% increments, an integer seed from 0 to 4294967295, and opacity 0–100%.' : unsharp ? 'Use Amount 0–500% in exact 0.01% increments, finite Sigma 0–50 source px, integer Threshold 0–255, and opacity 0–100%.' : spatial ? `Enter a finite sigma from 0 to ${kind === 'sharpen' ? 10 : 50} source pixels, and opacity from 0 to 100%. Values are not rounded to slider steps.` : isTonalKind(kind) ? tonalValidationMessage(kind) : `Use the allowed value range${kind === 'median' ? ' and an odd window size' : ''}. Levels and curves need ordered points. Mixer percentages use exact 0.01% steps within −200–200; gradient stops must strictly increase from 0% to 100%.`}</p>}
    {atLimit && <p className="property-hint">Filter limit reached: {capabilities.limits?.maxFiltersPerLayer || 8} per layer, {capabilities.limits?.maxFiltersPerDocument || 64} per document.</p>}
    {filters.length > 0 && <p className="filter-warning">{filterStackActionHint(bakingSupported, 'painting, filling, extracting, placing, or repairing source cutout alpha')} Layer masks, transforms and outside effects remain editable. Other tool restrictions still apply.</p>}
  </section>;
}
