import { nextNoiseSeed, parseNoiseDraft, type NoiseDraft } from './noise';

export function NoiseControls({ draft, onChange, disabled = false, blendMode = 'normal' }: { draft: NoiseDraft; onChange: (draft: NoiseDraft) => void; disabled?: boolean; blendMode?: string }) {
  const parsed = parseNoiseDraft(draft);
  return <div className="noise-controls" role="region" aria-label="Add Noise settings">
    <label className="field-label">Amount, %<input aria-label="Noise amount percent" disabled={disabled} type="number" min="0" max="400" step="0.01" value={draft.amount} onChange={event => onChange({ ...draft, amount: event.target.value })} /></label>
    <input aria-label="Noise amount slider" disabled={disabled} type="range" min="0" max="400" step="1" value={Number.isFinite(Number(draft.amount)) ? Number(draft.amount) : 0} onChange={event => onChange({ ...draft, amount: event.target.value })} />
    <label className="field-label">Distribution<select aria-label="Noise distribution" disabled={disabled} value={draft.distribution} onChange={event => onChange({ ...draft, distribution: event.target.value as NoiseDraft['distribution'] })}><option value="uniform">Uniform</option><option value="gaussian">Gaussian</option></select></label>
    <label className="noise-monochromatic"><input aria-label="Noise monochromatic" disabled={disabled} type="checkbox" checked={draft.monochromatic} onChange={event => onChange({ ...draft, monochromatic: event.target.checked })} />Monochromatic</label>
    <div className="noise-seed"><label className="field-label">Pattern seed<input aria-label="Noise pattern seed" disabled={disabled} type="number" min="0" max="4294967295" step="1" value={draft.seed} onChange={event => onChange({ ...draft, seed: event.target.value })} /></label><button className="button mini subtle" type="button" disabled={disabled} onClick={() => onChange({ ...draft, seed: nextNoiseSeed(draft.seed) })}>New pattern</button></div>
    <div className="spatial-filter-guidance"><p>Adds repeatable grain to source RGB and keeps transparency.</p><p>New pattern changes the seed draft. Apply to view the pattern.</p>{parsed?.amount === 0 && <p className="spatial-identity-note">{blendMode === 'normal' ? 'Amount 0 leaves pixels unchanged in Normal mode.' : 'Amount 0 adds no noise. Filter blending can still change colors.'} After saving, an enabled filter still belongs to the stack. Bake or Clear removes it before source editing.</p>}</div>
    <details className="noise-help"><summary>How Add Noise works</summary><div className="spatial-filter-guidance"><p>The saved seed repeats the same pattern across previews, exports, history and recipes. New pattern changes only this draft; Apply saves it.</p><p>Uniform spreads changes within a range. Gaussian uses a defined, bounded discrete normal distribution with wider tails. Equal Amount produces different spread in the two modes.</p><p>Monochromatic adds the same change to RGB before clipping. It does not make the image grayscale or guarantee unchanged hue.</p><p>Noise follows source coordinates before transforms. Alpha stays exact; fully transparent RGB stays ungraded. The selection is ignored; masks and layer opacity apply afterward.</p><p>Amount controls the noise before clipping. Filter blending runs next; filter opacity blends its finished result separately. Larger source images and multiple active filters use more work; a limit refusal keeps the saved stack unchanged.</p></div></details>
  </div>;
}
