import { useRef } from 'react';
import { parsePhotoFilterDraft, photoFilterColor, photoFilterDensity, photoFilterIdentity, PHOTO_FILTER_DEFAULTS, toPhotoFilterDraft, type PhotoFilterDraft } from './photo-filter';
import './photo-filter.css';
export function PhotoFilterControls({ draft, onChange, disabled = false, source = false, blendMode = 'normal' }: { draft: PhotoFilterDraft; onChange: (draft: PhotoFilterDraft) => void; disabled?: boolean; source?: boolean; blendMode?: string }) {
  const color = photoFilterColor(draft.color), parsed = parsePhotoFilterDraft(draft), lastColor = useRef(PHOTO_FILTER_DEFAULTS.color);
  if (color) lastColor.current = color;
  const change = (next: PhotoFilterDraft) => { if (!disabled) onChange(next); };
  return <section className="photo-filter-controls" aria-label="Photo Filter settings">
    <label className="field-label">Filter color<span className="photo-filter-color-row"><input type="color" aria-label="Choose Photo Filter color" value={color || lastColor.current} disabled={disabled} onChange={event => change({ ...draft, color: event.target.value })} /><input type="text" aria-label="Photo Filter color hex" value={draft.color} spellCheck={false} autoCapitalize="none" aria-invalid={!color} disabled={disabled} onChange={event => change({ ...draft, color: event.target.value })} /></span></label>
    <label className="field-label">Density, %<input type="text" inputMode="decimal" aria-label="Photo Filter density percent" value={draft.density} aria-invalid={photoFilterDensity(draft.density) === undefined} disabled={disabled} onChange={event => change({ ...draft, density: event.target.value })} /></label>
    <label className="photo-filter-preserve"><input type="checkbox" aria-label="Preserve Photo Filter Luminosity" checked={draft.preserveLuminosity} disabled={disabled} onChange={event => change({ ...draft, preserveLuminosity: event.target.checked })} />Preserve Luminosity</label>
    <button className="button mini subtle" type="button" disabled={disabled} onClick={() => change(toPhotoFilterDraft())}>Reset Photo Filter</button>
    {!parsed && <p className="inline-panel-error">Use a six-digit #rrggbb color and Density 0–100% in exact 0.01% increments.</p>}
    {disabled && <p className="tonal-unavailable">These settings are read-only here.</p>}
    <p className="property-hint">Apply a colored filter to RGB. Transparency stays unchanged.</p>
    {parsed && photoFilterIdentity(parsed) && <p className="property-hint photo-filter-identity">These settings produce the original-color candidate.{source && blendMode !== 'normal' ? ' Filter blending can still change colors.' : ' The color treatment leaves RGB unchanged.'}</p>}
    <details className="photo-filter-help"><summary>How Photo Filter works</summary><p>Density controls colored transmission, not a solid-color fill. Turning off Preserve Luminosity can darken the image; black stays black. Density 100% does not mean replacement with the chosen color.</p><p>Preserve Luminosity restores weighted encoded-RGB brightness before final rounding. Colors near the RGB boundary may lose chroma to fit. This is not calibrated white balance, perceptual lightness, linear-light optics or Photoshop pixel parity.</p><p>With preservation on, white and saturated primary colors remain unchanged, while neutral midtones can gain color. If the filter transmits none of an input color at full density, the preserved result is the original RGB. A black filter therefore preserves the original when preservation is on.</p><p>Density zero, a white filter, or a gray filter with preservation on produces the original-color candidate.{source && ' Non-Normal filter blending can still change that candidate. The entry remains editable and still counts for source-edit and Bake rules.'}</p><p>{source ? 'Runs on source RGB before transforms. The effect mask mixes the completed stack; the layer mask controls visibility. Alpha and fully transparent RGB stay unchanged.' : 'Creates or updates an editable adjustment. Its mask and opacity control the visible effect; alpha and fully transparent RGB stay unchanged.'} A work-limit refusal keeps saved settings intact; the values are never reduced or retried automatically.</p></details>
  </section>;
}
