import { useState } from 'react';
import type { SelectiveColorRange } from './api';
import { SELECTIVE_RANGES, invalidSelectiveRanges, parseSelectiveColorDraft, selectivePercentage, toSelectiveColorDraft, type SelectiveColorDraft } from './selective-color';
import './selective-color.css';
const title = (name: string) => name[0].toUpperCase() + name.slice(1);
export function SelectiveColorControls({ draft, onChange, disabled = false, source = false, blendMode = 'normal' }: { draft: SelectiveColorDraft; onChange: (draft: SelectiveColorDraft) => void; disabled?: boolean; source?: boolean; blendMode?: string }) {
  const [range, setRange] = useState<SelectiveColorRange>('reds');
  const invalid = invalidSelectiveRanges(draft), parsed = parseSelectiveColorDraft(draft), identity = parsed && SELECTIVE_RANGES.every(name => parsed[name].every(value => value === 0));
  return <section className="selective-color-controls" aria-label="Selective Color settings">
    <label className="field-label">Color range<select aria-label="Selective Color range" value={range} onChange={event => setRange(event.target.value as SelectiveColorRange)}>{SELECTIVE_RANGES.map(name => <option key={name} value={name}>{title(name)}{invalid.includes(name) ? ' · incomplete' : ''}</option>)}</select></label>
    <label className="field-label">Method<select aria-label="Selective Color method" disabled={disabled} value={draft.method} onChange={event => onChange({ ...draft, method: event.target.value as SelectiveColorDraft['method'] })}><option value="relative">Relative</option><option value="absolute">Absolute</option></select></label>
    <div className="selective-color-inks">{['Cyan', 'Magenta', 'Yellow', 'Black'].map((ink, index) => <label key={ink}>{ink}<span><input aria-label={`${title(range)} ${ink.toLowerCase()} percent`} type="text" inputMode="decimal" disabled={disabled} value={draft[range][index]} aria-invalid={selectivePercentage(draft[range][index]) === undefined} onChange={event => onChange({ ...draft, [range]: draft[range].map((value, i) => i === index ? event.target.value : value) })} />%</span></label>)}</div>
    <div className="selective-color-resets"><button type="button" className="button mini subtle" disabled={disabled} onClick={() => onChange({ ...draft, [range]: ['0', '0', '0', '0'] })}>Reset range</button><button type="button" className="button mini subtle" disabled={disabled} onClick={() => onChange(toSelectiveColorDraft())}>Reset all ranges</button></div>
    {invalid.length > 0 && <p className="inline-panel-error">Complete {invalid.map(title).join(', ')} before applying. Use −100 to 100% in exact 0.01% increments.</p>}
    {disabled && <p className="tonal-unavailable">These settings are read-only here. You can inspect every color range; saved values stay unchanged.</p>}
    <p className="property-hint">Adjust selected color ranges while retaining the other range settings.</p>
    {identity && <p className="property-hint">All values are zero.{source && blendMode !== 'normal' ? ' Filter blending can still change colors.' : ' The color correction leaves pixels unchanged.'}</p>}
    <details className="selective-color-help"><summary>How Selective Color works</summary><p>Positive Cyan, Magenta and Yellow reduce red, green and blue. Virtual Black adds to each of those corrections; it is not a separate multiplicative ink stage.</p><p>Relative scales correction by each channel’s distance from white. White therefore stays white, and positive Black cannot darken a fully saturated pure primary. Absolute can change those colors.</p><p>Prism partitions the original RGB among nine ranges, combines their corrections, then rounds once. This native RGB treatment is not a print CMYK conversion or a promise of Photoshop pixel parity.</p><p>{source ? 'Runs on source RGB before transforms. Alpha and fully transparent RGB stay unchanged; the filter effect mask blends the completed stack, then the layer mask controls visibility. A zero correction can still change colors with a non-Normal filter blend.' : 'Creates or updates an editable adjustment over the canvas. The adjustment mask and opacity control its visible effect.'}</p><p>Strong settings can clip color detail. Work limits may refuse a change; existing settings remain intact and values are never reduced automatically.</p></details>
  </section>;
}
