import { useState } from 'react';
import type { HueSaturationRange } from './api';
import { HSL_RANGES, invalidTargetedHSLRanges, parseTargetedHSLDraft, targetedHSLNumber, toTargetedHSLDraft, type TargetedHSLDraft } from './targeted-hsl';
import './targeted-hsl.css';
const title = (name: string) => name[0].toUpperCase() + name.slice(1);
export function TargetedHSLControls({ draft, onChange, disabled = false, source = false, blendMode = 'normal' }: { draft: TargetedHSLDraft; onChange: (draft: TargetedHSLDraft) => void; disabled?: boolean; source?: boolean; blendMode?: string }) {
  const [range, setRange] = useState<HueSaturationRange>('master');
  const invalid = invalidTargetedHSLRanges(draft), parsed = parseTargetedHSLDraft(draft), identity = parsed && HSL_RANGES.every(name => parsed[name].every(value => value === 0));
  return <section className="targeted-hsl-controls" aria-label="Hue / Saturation settings">
    <label className="field-label">Color range<select aria-label="Hue / Saturation range" value={range} onChange={event => setRange(event.target.value as HueSaturationRange)}>{HSL_RANGES.map(name => <option key={name} value={name}>{title(name)}{invalid.includes(name) ? ' · incomplete' : ''}</option>)}</select></label>
    <div className="targeted-hsl-values">{['Hue', 'Saturation', 'Lightness'].map((channel, index) => <label key={channel}>{channel}<span><input aria-label={`${title(range)} ${channel.toLowerCase()} ${index === 0 ? 'degrees' : 'percent'}`} type="text" inputMode="decimal" disabled={disabled} value={draft[range][index]} aria-invalid={targetedHSLNumber(draft[range][index], index) === undefined} onChange={event => onChange({ ...draft, [range]: draft[range].map((value, i) => i === index ? event.target.value : value) })} />{index === 0 ? '°' : '%'}</span></label>)}</div>
    <div className="targeted-hsl-resets"><button type="button" className="button mini subtle" disabled={disabled} onClick={() => onChange({ ...draft, [range]: ['0', '0', '0'] })}>Reset range</button><button type="button" className="button mini subtle" disabled={disabled} onClick={() => onChange(toTargetedHSLDraft())}>Reset all ranges</button></div>
    {invalid.length > 0 && <p className="inline-panel-error">Complete {invalid.map(title).join(', ')} before applying. Use Hue −180 to 180°, Saturation and Lightness −100 to 100%, in exact 0.01 increments.</p>}
    {disabled && <p className="tonal-unavailable">These settings are read-only here. You can inspect every color range; saved values stay unchanged.</p>}
    <p className="property-hint">Adjust Master or a color range. All range settings stay together.</p>
    {identity && <p className="property-hint">All values are zero.{source && blendMode !== 'normal' ? ' Filter blending can still change colors.' : ' The color correction leaves pixels unchanged.'}</p>}
    <details className="targeted-hsl-help"><summary>How Hue / Saturation works</summary><p>Named ranges follow this entry’s input hue. Nearby ranges can contribute together. Master and named changes combine from those same input colors; a Master hue shift does not retarget the named rows.</p><p>Saturation is proportional. With other rows at zero and full range influence, +100% doubles current HSL saturation up to its limit; it does not set every color to full saturation. −100% removes saturation while keeping HSL lightness. Exact gray stays gray under Hue and Saturation.</p><p>Hue and Saturation can fully target a matching dark or pale hue. Named Lightness is gentler on low-chroma colors, including dark, pale and nearly gray colors, so its endpoints may not reach black or white. Master Lightness also changes neutrals and, on its own, reaches black at −100% and white at +100%.</p><p>This fixed-range native RGB/HSL treatment is separate from the older scalar Hue and Saturation controls. It is not perceptual exposure correction or Photoshop pixel parity. Colorize and adjustable range falloffs are not included.</p><p>{source ? 'Runs on source RGB before transforms. Alpha and fully transparent RGB stay unchanged; the effect mask blends the completed filter stack, then the layer mask controls visibility. A zero correction can still change colors with non-Normal filter blending.' : 'Creates or updates an editable adjustment over the canvas. The adjustment mask and opacity control its visible effect.'}</p><p>Strong settings can lose color detail. A work-limit refusal keeps the saved settings intact; values are never reduced or retried automatically.</p></details>
  </section>;
}
