import { useState } from 'react';
import { Check, Type } from 'lucide-react';
import type { Backend, Document, Layer } from './api';
import type { RunCommand } from './CanvasTools';
import { captureGesture } from './gesture';
import './text-spacing.css';

type TextSettings = { text: string; fontSize: number; color: string; fontFamily: NonNullable<Layer['fontFamily']>; fontWeight: 'normal' | 'bold'; fontStyle: 'normal' | 'italic'; align: 'left' | 'center' | 'right'; x: number; y: number };
type Spacing = { tracking: string; leading: string; auto: boolean };
const numeric = (value: string) => value.trim() !== '' && Number.isFinite(Number(value));
const units = (capabilities?: Backend) => ({ tracking: capabilities?.id === 'native' && capabilities.textSpacingProperties?.includes('tracking') && capabilities.textTrackingUnits === 'thousandths-em', leading: capabilities?.id === 'native' && capabilities.textSpacingProperties?.includes('leading') && capabilities.textLeadingUnits === 'source-pixels' });
function spacingValid(spacing: Spacing, capabilities?: Backend) { const can = units(capabilities); return (!can.tracking || numeric(spacing.tracking) && Number.isInteger(Number(spacing.tracking)) && Number(spacing.tracking) >= -1000 && Number(spacing.tracking) <= 1000) && (!can.leading || spacing.auto || numeric(spacing.leading) && Number(spacing.leading) >= 1 && Number(spacing.leading) <= 2000); }
function spacingArgs(spacing: Spacing, capabilities?: Backend) { const can = units(capabilities); return { ...(can.tracking ? { tracking: Number(spacing.tracking) } : {}), ...(can.leading ? { leading: spacing.auto ? null : Number(spacing.leading) } : {}) }; }
function TextSpacing({ spacing, setSpacing, fontSize, capabilities }: { spacing: Spacing; setSpacing: (next: Spacing) => void; fontSize: number; capabilities?: Backend }) {
  const can = units(capabilities), autoStep = Number.isFinite(fontSize) ? fontSize * 1.2 : null;
  if (!can.tracking && !can.leading) return null;
  return <section className="text-spacing" aria-label="Text spacing"><div className="section-heading"><span>Spacing</span></div><div className="text-spacing-fields">{can.tracking && <label className="field-label">Tracking, 1/1000 em<input aria-label="Text tracking" type="number" min="-1000" max="1000" step="1" required value={spacing.tracking} onChange={event => setSpacing({ ...spacing, tracking: event.target.value })} /></label>}{can.leading && <><label className="field-label">Line spacing<select aria-label="Text line spacing mode" value={spacing.auto ? 'auto' : 'explicit'} onChange={event => setSpacing({ ...spacing, auto: event.target.value === 'auto', ...(event.target.value === 'explicit' && spacing.auto ? { leading: String(Number((autoStep ?? 76.8).toPrecision(15))) } : {}) })}><option value="auto">Auto · 1.2 × size</option><option value="explicit">Explicit pixels</option></select></label>{!spacing.auto && <label className="field-label">Baseline step, source px<input aria-label="Text line spacing pixels" type="number" min="1" max="2000" step="any" required value={spacing.leading} onChange={event => setSpacing({ ...spacing, leading: event.target.value })} /></label>}</>}</div>{can.leading && <p className="property-hint">{spacing.auto ? `Auto baseline step: ${autoStep === null ? '—' : Number(autoStep.toFixed(6))} source px.` : 'Explicit baseline spacing stays fixed when font size changes.'} Blank lines count.</p>}{can.tracking && <p className="property-hint">Tracking scales with type size. Spacing is applied before layer transforms.</p>}{!spacingValid(spacing, capabilities) && <p className="inline-panel-error">{can.tracking && 'Tracking: whole values −1000 to 1000. '}{can.leading && 'Explicit line spacing: 1–2000 px.'}</p>}</section>;
}
function validText(settings: TextSettings, width: number, height: number) { return settings.text.trim().length > 0 && settings.text.length <= 2000 && Number.isFinite(settings.fontSize) && settings.fontSize >= 1 && settings.fontSize <= 1000 && Number.isInteger(settings.x) && settings.x >= 0 && settings.x < width && Number.isInteger(settings.y) && settings.y >= 0 && settings.y < height; }
function TextFields({ settings, setSettings, width, height, editing, native }: { settings: TextSettings; setSettings: (value: TextSettings) => void; width: number; height: number; editing: boolean; native: boolean }) {
  return <><label className="field-label">{editing ? 'Text' : 'Your text'}<textarea aria-label={editing ? 'Edit text content' : 'Your text'} autoFocus={!editing} required maxLength={2000} rows={3} value={settings.text} onChange={event => setSettings({ ...settings, text: event.target.value })} /></label><div className={editing ? 'pro-form-grid' : 'form-grid'}>{native && <label className="field-label">Typeface<select aria-label={editing ? 'Text typeface' : 'New text typeface'} value={settings.fontFamily} onChange={event => setSettings({ ...settings, fontFamily: event.target.value as TextSettings['fontFamily'] })}><option value="sans-serif">Sans serif</option><option value="serif">Serif</option><option value="Fraunces">Fraunces · retro serif</option><option value="monospace">Monospace</option></select></label>}<label className="field-label">{editing ? 'Size, px' : 'Font size, px'}<input aria-label={editing ? 'Edit text size' : 'Font size, px'} type="number" min="1" max="1000" step="any" required value={Number.isNaN(settings.fontSize) ? '' : settings.fontSize} onChange={event => setSettings({ ...settings, fontSize: event.target.valueAsNumber })} /></label><label className="field-label">Color<input aria-label={editing ? 'Edit text color' : 'Color'} type="color" value={settings.color} onChange={event => setSettings({ ...settings, color: event.target.value })} /></label>{editing && <label className="field-label">Alignment<select aria-label="Text alignment" value={settings.align} onChange={event => setSettings({ ...settings, align: event.target.value as TextSettings['align'] })}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label>}<label className="field-label">{editing ? 'X, source px' : 'X position, px'}<input aria-label={editing ? 'Text X position' : 'X position, px'} type="number" min="0" max={width - 1} step="1" required value={Number.isNaN(settings.x) ? '' : settings.x} onChange={event => setSettings({ ...settings, x: event.target.valueAsNumber })} /></label><label className="field-label">{editing ? 'Y, source px' : 'Y position, px'}<input aria-label={editing ? 'Text Y position' : 'Y position, px'} type="number" min="0" max={height - 1} step="1" required value={Number.isNaN(settings.y) ? '' : settings.y} onChange={event => setSettings({ ...settings, y: event.target.valueAsNumber })} /></label></div>{native && <div className="text-style-options"><label><input type="checkbox" checked={settings.fontWeight === 'bold'} onChange={event => setSettings({ ...settings, fontWeight: event.target.checked ? 'bold' : 'normal' })} /><strong>Bold</strong></label><label><input type="checkbox" checked={settings.fontStyle === 'italic'} onChange={event => setSettings({ ...settings, fontStyle: event.target.checked ? 'italic' : 'normal' })} /><em>Italic</em></label></div>}</>;
}
export function TextProperties(props: { layer: Layer; document: Document; busy: boolean; run: RunCommand; capabilities?: Backend }) {
  const { document, layer, capabilities } = props;
  return <TextEditor key={`${document.backend}:${document.id}:${document.revision}:${layer.id}:${capabilities?.textSpacingProperties?.join(',')}:${capabilities?.textTrackingUnits}:${capabilities?.textLeadingUnits}`} {...props} />;
}
function TextEditor({ layer, document, busy, run, capabilities }: { layer: Layer; document: Document; busy: boolean; run: RunCommand; capabilities?: Backend }) {
  const [settings, setSettings] = useState<TextSettings>({ text: layer.text || '', fontSize: layer.fontSize ?? 64, color: layer.color || '#ffffff', fontFamily: layer.fontFamily || 'sans-serif', fontWeight: layer.fontWeight || 'normal', fontStyle: layer.fontStyle || 'normal', align: layer.align || 'left', x: layer.x ?? 0, y: layer.y ?? 0 });
  const [spacing, setSpacing] = useState<Spacing>({ tracking: String(layer.tracking ?? 0), leading: String(layer.leading ?? (layer.fontSize ?? 64) * 1.2), auto: layer.leading === undefined });
  const width = layer.width ?? document.width, height = layer.height ?? document.height;
  const valid = validText(settings, width, height) && spacingValid(spacing, capabilities);
  return <form className="panel-section editable-text" onSubmit={event => { event.preventDefault(); if (valid && !busy && !layer.protected) void run('update_text', { layerId: layer.id, ...settings, ...spacingArgs(spacing, capabilities) }, 'Updating text', captureGesture(document, layer.id)); }}><div className="section-heading"><span>Edit typography</span><Type size={14} /></div><fieldset className="text-edit-fields" disabled={busy || layer.protected}><TextFields settings={settings} setSettings={setSettings} width={width} height={height} editing native={document.backend === 'native'} /><TextSpacing spacing={spacing} setSpacing={setSpacing} fontSize={settings.fontSize} capabilities={capabilities} /></fieldset><p className="property-hint">Positions and spacing use the {width} × {height} px source canvas, before transforms.</p>{layer.protected && <p className="property-hint">Unprotect this layer to change its text or typography.</p>}<button className="button secondary wide" type="submit" disabled={busy || layer.protected || !valid}><Check size={13} />Update text layer</button></form>;
}
export function TextCreationForm({ document, selectedLayerId, busy, run, capabilities, initial, onComplete }: { document: Document; selectedLayerId?: string; busy: boolean; run: RunCommand; capabilities?: Backend; initial: TextSettings; onComplete: (settings: TextSettings) => void }) {
  const [settings, setSettings] = useState<TextSettings>({ ...initial, x: Math.max(0, Math.min(document.width - 1, Math.round(initial.x))), y: Math.max(0, Math.min(document.height - 1, Math.round(initial.y))) });
  const [spacing, setSpacing] = useState<Spacing>({ tracking: '0', leading: String(initial.fontSize * 1.2), auto: true });
  const valid = validText(settings, document.width, document.height) && spacingValid(spacing, capabilities);
  return <><span className="eyebrow">WORDS, WITH FEELING</span><h1 id="modal-title">Say something.</h1><p className="modal-intro">Add a text layer to your composition.</p><form onSubmit={event => { event.preventDefault(); if (!valid || busy) return; const { text, x, y, fontSize, color, fontFamily, fontWeight, fontStyle } = settings; void run('add_text', { text, x, y, fontSize, color, ...(document.backend === 'native' ? { fontFamily, fontWeight, fontStyle } : {}), ...spacingArgs(spacing, capabilities) }, 'Adding text', captureGesture(document, selectedLayerId)).then(result => { if (result) onComplete(settings); }); }}><fieldset className="text-edit-fields" disabled={busy}><TextFields settings={settings} setSettings={setSettings} width={document.width} height={document.height} editing={false} native={document.backend === 'native'} /><TextSpacing spacing={spacing} setSpacing={setSpacing} fontSize={settings.fontSize} capabilities={capabilities} /></fieldset><button className="button primary wide" disabled={busy || !valid} type="submit"><Type size={15} />Add text layer</button></form></>;
}
