import { chromium, expect as baseExpect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { createCompanion } from '../server/index.mjs';

// Full HTTP chat, scoped tool calls, native editor and generation manager.
// The injected agent follows test-authored plans by call order, never keywords.
// Image bytes are authored locally; no real Codex or image-provider call runs.
const startedAt = Date.now(), expect = baseExpect.configure({ timeout: 20000 }), artifacts = path.resolve('test-results'), dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'prism-chat-browser-'));
await fs.mkdir(artifacts, { recursive: true });
let available = true, keyReads = 0, providerCalls = 0, imageCalls = 0;
const plans = [], agentCalls = [];
const color = Buffer.alloc(96 * 64 * 4); for (let i = 0; i < color.length; i += 4) color.set([20, 60, 100, 255], i);
const image = await sharp(color, { raw: { width: 96, height: 64, channels: 4 } }).png().toBuffer();
async function tool(ctx, name, args = {}) {
 const response = await fetch(`${ctx.toolContext.baseUrl}/api/chat/${ctx.turn.id}/tool`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${ctx.toolContext.capabilityToken}` }, body: JSON.stringify({ name, arguments: args, callId: randomUUID() }) });
 const value = await response.json(); assert.equal(response.ok, true); assert.notEqual(value.isError, true, JSON.stringify(value.structuredContent)); return value.structuredContent;
}
const execute = (ctx, name, args = {}) => tool(ctx, 'prism_execute', { name, args });
const adapter = { check: async () => ({ available }), run: async ctx => { agentCalls.push(ctx); const plan = plans.shift(); assert.ok(plan, 'Every injected agent turn needs an explicit test plan'); return plan(ctx); } };
const companion = await createCompanion({ dataDir, port: 0, chatEnabled: true, chatAdapter: adapter, codexWorkerEnabled: true, codexImageAdapter: { check: async () => ({ available: true }), generate: async () => { imageCalls++; return image; } }, getImageKey: async () => { keyReads++; return null; }, imageProvider: async () => { providerCalls++; throw Error('No API provider in chat browser test'); } });
const base = (await companion.native.execute('import_image', { name: 'Chat editing context', data: image.toString('base64'), mimeType: 'image/png' })).document;
const other = (await companion.native.execute('import_image', { name: 'Another document', data: image.toString('base64'), mimeType: 'image/png' })).document;
const baseUrl = `http://127.0.0.1:${await companion.listen()}`;
const browser = await chromium.launch({ headless: true, channel: 'chrome' }), page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' }); page.setDefaultTimeout(20000);
const errors = [], external = [], submissions = [], passed = [];
page.on('pageerror', error => errors.push(error.message)); page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith(baseUrl)) external.push(request.url()); if (request.method() === 'POST' && request.url() === `${baseUrl}/api/chat`) submissions.push(request.postDataJSON()); }); await page.route('https://**', route => route.abort());
const panel = page.getByRole('region', { name: 'Chat with Codex', exact: true }), input = () => panel.getByLabel('Message Codex', { exact: true }), send = () => panel.getByRole('button', { name: 'Send message to Codex', exact: true });
const turn = message => panel.getByRole('article', { name: `Request: ${message}`, exact: true });
const tab = name => page.locator('.inspector-tabs').getByRole('button', { name, exact: true }).click();
const current = async id => (await companion.native.execute('get_document', { documentId: id || await page.getByLabel('Open document').inputValue() })).document;
const turns = async () => (await companion.chat.list()).turns;
const replyReady = message => expect(turn(message).locator('.chat-turn-status')).toContainText('Reply ready');
async function sendMessage(message) { await input().fill(message); await send().click(); await expect(turn(message)).toBeVisible(); }
async function select(id) { await page.getByLabel('Open document').selectOption(id); await expect(page.locator('.save-status .spin')).toHaveCount(0); }
async function pixels(id) { const result = await companion.native.execute('export_document', { documentId: id, format: 'png' }); return sharp(Buffer.from(result.data, 'base64')).ensureAlpha().raw().toBuffer(); }
const waitAbort = signal => new Promise((resolve, reject) => { if (signal.aborted) return reject(Error('Stopped')); signal.addEventListener('abort', () => reject(Error('Stopped')), { once: true }); });
const check = text => { passed.push(text); console.log('Verified:', text); };
try {
 await page.goto(baseUrl, { waitUntil: 'networkidle' }); await select(base.id); await expect(panel).toBeVisible(); await expect(page.locator('.assistant-area')).toHaveCount(0); await expect(page.locator('.generation-header-button')).toHaveCount(0); await expect(panel.locator('.chat-context')).toContainText(base.name); await expect(panel.getByRole('button', { name: 'Open image for chat', exact: true })).toBeVisible();
 await input().fill('Keep this unfinished draft'); await tab('Layers'); await expect(page.getByLabel('Layer name', { exact: true })).toBeVisible(); await tab('Chat'); await expect(input()).toHaveValue('Keep this unfinished draft');
 const editMessage = 'Make the colors a negative.\nKeep the original layer editable.';
 plans.push(async ctx => { const before = (await execute(ctx, 'get_document', { documentId: ctx.turn.documentId })).document; await ctx.onEvent({ label: 'Applying an editable color adjustment', status: 'running' }); await execute(ctx, 'add_adjustment', { documentId: before.id, expectedRevision: before.revision, kind: 'invert', value: 100 }); return { reply: 'Added an editable Invert adjustment above the original layer.' }; });
 await input().fill('Make the colors a negative.'); await input().press('Shift+Enter'); await input().press('KeyK'); await input().fill(editMessage); const beforeSend = submissions.length; await input().press('Enter'); await replyReady(editMessage); assert.equal(submissions.length, beforeSend + 1); assert.equal(submissions.at(-1).message, editMessage); assert.equal(submissions.at(-1).documentId, base.id); assert.equal(submissions.at(-1).selectedLayerId, base.layers[0].id); assert.ok(submissions.at(-1).requestId); await expect(turn(editMessage).getByLabel('Work updates')).toContainText('Applying an editable color adjustment'); const edited = await current(base.id); assert.equal(edited.layers.length, 2); assert.deepEqual([...((await pixels(base.id)).subarray(0, 4))], [235, 195, 155, 255]); await expect(panel).toBeVisible();
 check('Chat replaces both competing entry points, shows existing image/layer context, retains drafts across manual tabs and sends Enter/Shift+Enter text unchanged to real native editing with visible work and reply');

 const generateMessage = 'Create a small original blue-green image.';
 plans.push(async ctx => { const generated = await tool(ctx, 'prism_generate_image', { prompt: 'Authored synthetic image fixture', size: 'auto', background: 'auto', scope: 'canvas' }); assert.equal(generated.job.status, 'succeeded', JSON.stringify(generated)); return { reply: 'Created the image as a new document.' }; });
 await sendMessage(generateMessage); await replyReady(generateMessage); const generatedTurn = (await turns()).find(item => item.message === generateMessage); assert.ok(generatedTurn.resultDocumentId); assert.equal(generatedTurn.generationJobIds.length, 1); await expect(page.getByLabel('Open document')).toHaveValue(generatedTurn.resultDocumentId); await expect(turn(generateMessage).getByRole('button', { name: 'Open result', exact: true })).toHaveCount(0); await expect(panel).toBeVisible(); assert.deepEqual(await pixels(generatedTurn.resultDocumentId), color);
 const mixedMessage = 'Create an image, then put editable words on top.';
 let mixedCreated, releaseMixed; const mixedGate = new Promise(resolve => releaseMixed = resolve);
 plans.push(async ctx => { assert.ok(ctx.history.some(item => item.content === generateMessage)); const result = await tool(ctx, 'prism_generate_image', { prompt: 'Second synthetic image fixture', size: 'auto', background: 'auto', scope: 'canvas' }); const d = result.document; mixedCreated = d.id; await Promise.race([mixedGate, waitAbort(ctx.signal)]); await execute(ctx, 'add_text', { documentId: d.id, expectedRevision: d.revision, text: 'Hello', x: 4, y: 4, fontSize: 16, color: '#ffffff' }); return { reply: 'Created an image and added a separate editable text layer.' }; });
 await sendMessage(mixedMessage); await expect.poll(() => mixedCreated, { timeout: 20_000 }).toBeTruthy(); const beforeMixed = await page.getByLabel('Open document').inputValue(); await expect(turn(mixedMessage).locator('.chat-turn-status')).toContainText('Working'); await expect(turn(mixedMessage).getByRole('progressbar', { name: 'Request progress' })).toBeVisible(); await page.waitForTimeout(1500); assert.equal(await page.getByLabel('Open document').inputValue(), beforeMixed, 'The canvas stays on the pre-edit image while chat works'); await expect(panel).toBeVisible(); releaseMixed(); await replyReady(mixedMessage); await expect(page.getByLabel('Open document')).toHaveValue(mixedCreated); await expect(turn(mixedMessage).getByRole('progressbar')).toHaveCount(0); const mixed = (await turns()).find(item => item.message === mixedMessage), mixedDoc = await current(mixed.resultDocumentId); assert.ok(mixedDoc.layers.some(layer => layer.type === 'text' && layer.text === 'Hello')); const mixedPixels = await pixels(mixed.resultDocumentId); await expect.poll(async () => { const src = await page.locator('.artboard img').getAttribute('src'); return Boolean(src && (await sharp(Buffer.from(src.split(',')[1], 'base64')).ensureAlpha().raw().toBuffer()).equals(mixedPixels)); }).toBe(true); assert.equal(mixed.generationJobIds.length, 1); assert.equal(imageCalls, 2); await expect(turn(mixedMessage).locator('.chat-image-job')).toContainText('Image added to workspace');
 check('The same chat route performs real generation and mixed generation/editing through scoped tools, retains conversation history and exposes only verified result IDs; new results open automatically and generation appears on the canvas before the agent finishes adding editable text');

 let releaseLate; const gate = new Promise(resolve => releaseLate = resolve); const lateMessage = 'Finish this edit while I inspect another document.';
 await select(base.id); plans.push(async ctx => { await gate; const d = (await execute(ctx, 'get_document', { documentId: ctx.turn.documentId })).document; await execute(ctx, 'add_text', { documentId: d.id, expectedRevision: d.revision, text: 'Late', x: 1, y: 1, fontSize: 12, color: '#ffffff' }); return { reply: 'Added the text to the original requested document.' }; }); await sendMessage(lateMessage); await expect(turn(lateMessage).locator('.chat-turn-status')).toContainText('Working'); await select(other.id); releaseLate(); await replyReady(lateMessage); await expect(page.getByLabel('Open document')).toHaveValue(base.id); await expect(panel.locator('.chat-context')).toContainText(base.name); assert.equal((await current(other.id)).layers.length, 1); await select(other.id);
 const stopMessage = 'Inspect the image and wait for my stop.'; plans.push(async ctx => { await execute(ctx, 'get_document', { documentId: ctx.turn.documentId }); await ctx.onEvent({ label: 'Waiting at the controlled test boundary', status: 'running' }); await waitAbort(ctx.signal); return { reply: 'Unreachable' }; }); await sendMessage(stopMessage); await expect(turn(stopMessage).getByLabel('Work updates')).toContainText('controlled test boundary'); await turn(stopMessage).getByRole('button', { name: `Stop request: ${stopMessage}`, exact: true }).click(); await expect(turn(stopMessage).locator('.chat-turn-status')).toContainText('Stopped'); await expect(turn(stopMessage)).toContainText('will not restart automatically'); await expect(turn(stopMessage).locator('.spin')).toHaveCount(0);
 const failMessage = 'Show an honest failure if the agent cannot finish.'; plans.push(async () => { throw Error('Synthetic unavailable runner'); }); await sendMessage(failMessage); await expect(turn(failMessage).locator('.chat-turn-status')).toContainText('Could not finish'); await expect(turn(failMessage)).toContainText('No automatic retry'); await expect(turn(failMessage).locator('.chat-open-result')).toHaveCount(0);
 check('Chat automatically displays its completed edit without changing the unrelated document; Stop ends progress without claiming rollback, and failures remain visible with no fabricated reply/result or automatic retry');

 const immediate = 'A quick edit whose delivery response is held.'; let releasePost, postStarted; const postGate = new Promise(resolve => releasePost = resolve), postSeen = new Promise(resolve => postStarted = resolve); let heldOnce = true;
 const heldRoute = async route => { if (heldOnce && route.request().method() === 'POST' && route.request().url() === `${baseUrl}/api/chat`) { heldOnce = false; const response = await route.fetch(); postStarted(); await postGate; await route.fulfill({ response }); } else await route.fallback(); }; await page.route('**/api/chat', heldRoute);
 plans.push(async ctx => { const d = (await execute(ctx, 'get_document', { documentId: ctx.turn.documentId })).document; await execute(ctx, 'add_adjustment', { documentId: d.id, expectedRevision: d.revision, kind: 'invert', value: 100 }); return { reply: 'The quick color edit is complete.' }; }); await input().fill(immediate); await send().click(); await postSeen; await replyReady(immediate); await expect(input()).toHaveValue(''); const imageBeforeRelease = await page.locator('.artboard img').getAttribute('src'); const previewRaw = await sharp(Buffer.from(imageBeforeRelease.split(',')[1], 'base64')).ensureAlpha().raw().toBuffer(); assert.deepEqual([...previewRaw.subarray(0, 4)], [235, 195, 155, 255]); releasePost(); await expect(send()).toBeDisabled(); await page.unroute('**/api/chat', heldRoute);
 let failedOnce = true; const uncertainRoute = async route => { if (failedOnce && route.request().method() === 'POST') { failedOnce = false; await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'TIMEOUT', message: 'Synthetic unconfirmed delivery' } }) }); } else await route.fallback(); }; await page.route('**/api/chat', uncertainRoute); const retryMessage = 'Retry this exact message once delivery is reviewed.'; plans.push(async () => ({ reply: 'The same request was accepted once.' })); await input().fill(retryMessage); await send().click(); await expect(panel).toContainText('Delivery is unconfirmed'); const failedRequest = submissions.at(-1); await expect(send()).toBeDisabled(); await tab('Layers'); await tab('Chat'); await expect(panel).toContainText('Delivery is unconfirmed'); await panel.getByRole('button', { name: 'Retry same message', exact: true }).click(); await replyReady(retryMessage); assert.equal(submissions.at(-1).requestId, failedRequest.requestId); assert.deepEqual(submissions.at(-1), failedRequest); assert.equal((await turns()).filter(t => t.message === retryMessage).length, 1); await page.unroute('**/api/chat', uncertainRoute);
 check('A first-observed terminal GET refreshes the canvas while POST is held; uncertain delivery survives panel switching and explicit retry reuses the exact requestId/context without duplicate execution');

 available = false; await companion.chat.check(); await panel.getByRole('button', { name: 'Refresh chat', exact: true }).click(); await expect(panel).toContainText('unavailable'); await input().fill('Retained while unavailable'); await expect(send()).toBeDisabled(); await expect(input()).toHaveValue('Retained while unavailable'); available = true; await companion.chat.check(); await panel.getByRole('button', { name: 'Refresh chat', exact: true }).click(); await expect(send()).toBeEnabled();
 await tab('Layers'); await page.getByLabel('Layer name', { exact: true }).fill('Manual tools still work'); await page.getByLabel('Layer name', { exact: true }).press('Enter'); await expect.poll(async () => (await current(other.id)).layers[0].name).toBe('Manual tools still work'); await tab('Chat'); await expect(input()).toHaveValue('Retained while unavailable');
 const chooser = page.waitForEvent('filechooser'); await panel.getByRole('button', { name: 'Open image for chat', exact: true }).click(); await (await chooser).setFiles([]); await expect(panel).toBeVisible(); await panel.getByRole('button', { name: 'Open image generation', exact: true }).click(); await expect(page.getByRole('dialog').getByLabel('Image generation prompt')).toHaveValue('Retained while unavailable'); await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
 check('Availability changes disable submission without losing drafts, Layers remains an operational manual editor, and Open image/Image options reuse existing secondary controls');

 await input().fill(''); await page.screenshot({ path: path.join(artifacts, 'chat-1440.png'), animations: 'disabled' }); await page.setViewportSize({ width: 900, height: 1000 }); await expect(input()).toBeInViewport(); await expect(send()).toBeInViewport(); await input().focus(); await expect(input()).toBeFocused(); await page.screenshot({ path: path.join(artifacts, 'chat-900.png'), animations: 'disabled' }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); assert.ok(await page.locator('.inspector').evaluate(el => el.scrollWidth <= el.clientWidth)); await page.reload({ waitUntil: 'networkidle' }); await expect(panel).toBeVisible(); await expect(turn(retryMessage)).toBeVisible(); assert.equal((await turns()).filter(t => t.message === retryMessage).length, 1); assert.deepEqual(errors, []); assert.deepEqual(external, []); assert.equal(keyReads, 0); assert.equal(providerCalls, 0);
 check('Conversation persists through reload; 900/1440px keyboard/composer layout has no overflow or competing generator, and the full workflow makes no real CLI/provider/key calls or browser errors');
 await fs.writeFile(path.join(artifacts, 'chat-browser-report.json'), JSON.stringify({ passed, durationMs: Date.now() - startedAt, agentCalls: agentCalls.length, syntheticImageCalls: imageCalls, actualCliCalls: 0, providerCalls, keyReads, browserErrors: errors }, null, 2)); console.log(`Chat browser passed ${passed.length} workflows.`);
} catch (error) { await page.screenshot({ path: path.join(artifacts, 'chat-browser-failure.png'), animations: 'disabled' }).catch(() => {}); console.error('Alerts:', await page.getByRole('alert').allTextContents().catch(() => [])); throw error; }
finally { await browser.close(); await companion.close(); await fs.rm(dataDir, { recursive: true, force: true }); }
