import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';
import { createCompanion } from '../server/index.mjs';

const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'prism-noise-ui-')), artifacts = path.resolve('test-results');
await fs.mkdir(artifacts, { recursive: true });
let keyReads = 0, providerCalls = 0;
const companion = await createCompanion({ dataDir, port: 0, getImageKey: async () => { keyReads++; return null; }, imageProvider: async () => { providerCalls++; throw Error('Noise tests stay local.'); }, segmentSubject: async () => { throw Error('Noise does not segment subjects.'); } });
const native = companion.native, get = async id => (await native.execute('get_document', { documentId: id })).document, edit = async (id, name, args = {}) => native.execute(name, { documentId: id, expectedRevision: (await get(id)).revision, ...args });
const defaults = { amount: 5, distribution: 'uniform', monochromatic: true, seed: 1 };
const width = 96, height = 72, raw = Buffer.alloc(width * height * 4);
for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) raw.set([20 + x % 200, (x + y) % 3 ? 190 : 30, (x + y) % 2 ? 10 : 240, [0, 1, 128, 255, 255][(x + y) % 5]], (y * width + x) * 4);
const encode = (bytes, w, h) => sharp(bytes, { raw: { width: w, height: h, channels: 4 } }).png().toBuffer(), png = await encode(raw, width, height);
async function fixture(name, bytes = png) { const d = (await native.execute('import_image', { name, data: bytes.toString('base64'), mimeType: 'image/png' })).document; return { id: d.id, target: d.layers[0].id }; }
async function seedFilter(d, parameters, extra = {}) { return edit(d.id, 'add_layer_filter', { layerId: d.target, kind: 'add_noise', value: 0, ...(parameters ? { parameters } : {}), ...extra }); }
const precision = await fixture('Noise authored precision'), sparse = await fixture('Sparse Noise settings'), alphaFixture = await fixture('Noise source-alpha stack'), caps = await fixture('Noise capability partitions'), recipe = await fixture('Noise saved recipe seeds'), lifecycle = await fixture('Noise completion identity'), alternate = await fixture('Other Noise document'), protectedTarget = await fixture('Protected Noise target'), prefix = await fixture('Protected lower pixels');
await edit(recipe.id, 'duplicate_layer', { layerId: recipe.target }); recipe.other = (await get(recipe.id)).layers.at(-1).id;
for (const d of [caps, lifecycle]) { await seedFilter(d, { amount: 12.34, distribution: 'gaussian', monochromatic: false, seed: 0 }); await edit(d.id, 'add_layer_filter', { layerId: d.target, kind: 'brightness', value: 12 }); }
await edit(lifecycle.id, 'add_paint_layer', { name: 'Other target layer' }); lifecycle.other = (await get(lifecycle.id)).layers.at(-1).id;
for (const d of [sparse, recipe]) {
  await seedFilter(d); await seedFilter(d, { seed: 0, monochromatic: false }, { enabled: false, opacity: .4 }); await seedFilter(d, { amount: 0, distribution: 'gaussian', seed: 4294967295 }, { enabled: false });
  const project = native.project(d.id), graph = structuredClone(project.states[project.cursor].graph), filters = graph.layers.find(layer => layer.id === d.target).filters;
  delete filters[0].parameters; filters[1].parameters = { seed: 0, monochromatic: false }; filters[2].parameters = { amount: 0, distribution: 'gaussian', seed: 4294967295 };
  await native.commit(project, graph, 'Valid sparse Noise parameters');
}
await edit(protectedTarget.id, 'set_layer_protection', { layerId: protectedTarget.target, protected: true });
await edit(prefix.id, 'set_layer_protection', { layerId: prefix.target, protected: true }); await edit(prefix.id, 'set_layer', { layerId: prefix.target, visible: false }); await edit(prefix.id, 'add_paint_layer', { name: 'Identity above protected source' }); prefix.target = (await get(prefix.id)).layers.at(-1).id; await seedFilter(prefix, { amount: 0 });
const alpha = Buffer.from(Array.from({ length: width * height }, (_, i) => [0, 64, 128, 255, 255, 255][i % 6]));
const project = native.project(alphaFixture.id), alphaGraph = structuredClone(project.states[project.cursor].graph); alphaGraph.layers[0].alphaAsset = await native.storeAlpha(alpha, width, height); await native.commit(project, alphaGraph, 'Separate alpha for Noise');
await edit(alphaFixture.id, 'set_layer_mask', { layerId: alphaFixture.target, mask: { shape: 'ellipse', x: 1.25, y: .5, width: 90, height: 68, feather: 1.25 } }); await edit(alphaFixture.id, 'modify_layer_mask', { layerId: alphaFixture.target, density: .7 }); await edit(alphaFixture.id, 'transform_layer', { layerId: alphaFixture.target, x: 2, y: 1, scaleX: 1, scaleY: 1, rotation: 0 }); await edit(alphaFixture.id, 'select_region', { shape: 'rectangle', x: 25, y: 15, width: 48, height: 38 });
const vectors = JSON.parse(await fs.readFile('tests/fixtures/noise/final-map-goldens.json', 'utf8')), vectorPng = await encode(Buffer.from(vectors.input), 3, 2), vectorFixture = await fixture('Independent final Noise vectors', vectorPng), equalFixture = await fixture('Same source different IDs', vectorPng);
const photo = await fs.readFile(path.resolve('tests/fixtures/tonal-color/astronaut.png')), photoHash = createHash('sha256').update(photo).digest('hex');
assert.equal(photoHash, '88431cd9653ccd539741b555fb0a46b61558b301d4110412b5bc28b5e3ea6cb5');
const photograph = await fixture('Photographic Add Noise', photo);
// On an 18MP source, two computing entries plus one identity use 306M work.
// Making the third compute would require 432M and must be refused unchanged.
const limitPng = await sharp({ create: { width: 6000, height: 3000, channels: 4, background: '#407090' } }).png().toBuffer();
const limit = await fixture('Noise cumulative work limit', limitPng);
await seedFilter(limit, { amount: 0 }); await seedFilter(limit, { amount: 0 }); await seedFilter(limit, { amount: 0 });
const assets = new Map();
for (const d of [precision, sparse, alphaFixture, caps, recipe, lifecycle, alternate, protectedTarget, prefix, vectorFixture, equalFixture, photograph, limit]) for (const layer of (await get(d.id)).layers) for (const hash of [layer.asset, layer.sourceAsset, layer.alphaAsset].filter(Boolean)) assets.set(hash, await fs.readFile(path.join(native.assetsDir, hash)));
const browser = await chromium.launch({ headless: true, channel: 'chrome' }), page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' }); page.setDefaultTimeout(15000);
const requests = [], errors = [], failedResponses = [], checkpoints = [];
page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !/^Failed to load resource: the server responded with a status of (400|409) /.test(message.text())) errors.push(message.text()); }); page.on('response', response => { if (response.status() >= 400) failedResponses.push({ status: response.status(), command: response.request().url().endsWith('/api/command') ? response.request().postDataJSON()?.command : 'other' }); }); page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/command')) requests.push(request.postDataJSON()); }); await page.route('https://**', route => route.abort());
let currentId = precision.id, targetId = precision.target;
const current = () => get(currentId), layer = async () => (await current()).layers.find(item => item.id === targetId), settled = () => expect(page.locator('.save-status .spin')).toHaveCount(0), panel = page.getByRole('region', { name: 'Layer filters', exact: true }), dialog = page.getByRole('dialog');
const amount = () => panel.getByLabel('Noise amount percent', { exact: true }), seed = () => panel.getByLabel('Noise pattern seed', { exact: true }), distribution = () => panel.getByLabel('Noise distribution', { exact: true }), mono = () => panel.getByLabel('Noise monochromatic', { exact: true }), pattern = () => panel.getByRole('button', { name: 'New pattern', exact: true }), reset = () => panel.getByRole('button', { name: 'Reset Add Noise', exact: true }), apply = () => panel.getByRole('button', { name: 'Apply filter changes', exact: true }), addButton = () => panel.getByRole('button', { name: 'Add layer filter', exact: true }), bake = () => panel.getByRole('button', { name: 'Bake filters', exact: true }), clear = () => panel.getByRole('button', { name: 'Clear filters', exact: true });
async function select(id) { targetId = id; await page.locator('.inspector-tabs').getByRole('button', { name: 'Layers', exact: true }).click(); await page.locator(`.layer-row[data-layer-id="${id}"]`).click(); }
async function open(d, id = d.target) { currentId = d.id; await page.getByLabel('Open document').selectOption(d.id); await settled(); await select(id); }
async function reopen(d, id = d.target) { await page.reload({ waitUntil: 'networkidle' }); await open(d, id); }
async function mutate(action) { await settled(); const before = await current(); await action(); await expect.poll(async () => (await get(before.id)).revision).toBeGreaterThan(before.revision); await settled(); const after = await get(before.id); assert.equal(after.revision, before.revision + 1); return after; }
const undo = () => mutate(() => page.getByRole('button', { name: 'Undo (⌘Z)', exact: true }).click()), redo = () => mutate(() => page.getByRole('button', { name: 'Redo (⇧⌘Z)', exact: true }).click());
async function choose(kind = 'add_noise') { await panel.getByRole('button', { name: 'New filter', exact: true }).click(); await panel.getByLabel('New layer filter kind').selectOption(kind); }
async function fields(parameters) { if (parameters.amount !== undefined) await amount().fill(String(parameters.amount)); if (parameters.seed !== undefined) await seed().fill(String(parameters.seed)); if (parameters.distribution !== undefined) await distribution().selectOption(parameters.distribution); if (parameters.monochromatic !== undefined) await mono().setChecked(parameters.monochromatic); }
async function values(parameters) { await expect(amount()).toHaveValue(String(parameters.amount)); await expect(seed()).toHaveValue(String(parameters.seed)); await expect(distribution()).toHaveValue(parameters.distribution); if (parameters.monochromatic) await expect(mono()).toBeChecked(); else await expect(mono()).not.toBeChecked(); }
async function add(parameters = {}, opacity) { await choose(); await fields(parameters); if (opacity !== undefined) await panel.getByLabel('Layer filter opacity', { exact: true }).fill(String(opacity)); return mutate(() => addButton().click()); }
async function editFilter(index, label = 'Add Noise') { await panel.getByRole('button', { name: `Edit filter ${index} ${label}`, exact: true }).click(); }
async function exported(id = currentId, name) { const result = await native.execute('export_document', { documentId: id, format: 'png' }), bytes = Buffer.from(result.data, 'base64'); if (name) await fs.writeFile(path.join(artifacts, name), bytes); return { bytes, data: await sharp(bytes).ensureAlpha().raw().toBuffer() }; }
async function sourceView(id, lid, view = 'source') { return (await native.execute('get_layer_preview', { documentId: id, layerId: lid, view, maxWidth: width })).data; }
const alphaBytes = data => Buffer.from(Array.from({ length: data.length / 4 }, (_, i) => data[i * 4 + 3]));
async function close() { await dialog.getByRole('button', { name: 'Close dialog', exact: true }).click(); }
async function recipes() { await page.getByRole('button', { name: /^Recipes(?: · outcome needs review)?$/ }).click(); await expect(dialog.getByRole('heading', { name: 'Edit recipes', exact: true })).toBeVisible(); }
async function dismiss() { if (await page.getByLabel('Dismiss notification').count()) await page.getByLabel('Dismiss notification').click(); }
async function hold(name, afterCommit = true) { let release, start, once = true; const gate = new Promise(resolve => release = resolve), started = new Promise(resolve => start = resolve); const handler = async route => { if (once && route.request().postDataJSON()?.command === name) { once = false; if (afterCommit) { const response = await route.fetch(); assert.equal(response.status(), 200); start(); await gate; await route.fulfill({ response }); } else { start(); await gate; await route.continue(); } } else await route.fallback(); }; await page.route('**/api/command', handler); return { started, release, done: () => page.unroute('**/api/command', handler) }; }
function checkpoint(message) { checkpoints.push(message); console.log(`Verified: ${message}`); }
try {
  await page.goto(`http://127.0.0.1:${await companion.listen()}`, { waitUntil: 'networkidle' }); await open(precision);
  await expect(panel.getByLabel('New layer filter kind').locator('option')).toHaveCount(32);
  const capabilities = await native.execute('capabilities'); assert.equal(capabilities.adjustmentKinds.length, 28); assert.equal(capabilities.adjustmentKinds.includes('add_noise'), false);
  await choose(); await values(defaults); await expect(seed()).toHaveAttribute('step', '1'); await expect(panel.locator('.noise-help')).not.toHaveAttribute('open', '');
  const draftBefore = await current(), writesBefore = requests.length;
  for (const [control, invalid] of [[amount, ''], [amount, '-1'], [amount, '400.01'], [amount, '5.001'], [amount, '5.000000000000001'], [amount, '1e309'], [seed, ''], [seed, '-1'], [seed, '.5'], [seed, '4294967296'], [seed, '1e309']]) { await reset().click(); await control().fill(invalid); await expect(addButton()).toBeDisabled(); }
  await reset().click(); await fields({ amount: 137.31, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); await panel.getByLabel('Layer filter opacity', { exact: true }).fill('37'); await reset().click(); await values(defaults); await expect(panel.getByLabel('Layer filter opacity', { exact: true })).toHaveValue('37');
  assert.equal((await current()).revision, draftBefore.revision); assert.equal(requests.length, writesBefore);
  await seed().fill('0'); await mutate(() => addButton().click()); assert.deepEqual((await layer()).filters[0].parameters, { ...defaults, seed: 0 }); assert.equal((await layer()).filters[0].value, 0);
  await amount().fill('5e0'); await seed().fill('0e0'); await expect(apply()).toBeDisabled(); await seed().fill('4294967295'); await mutate(() => apply().click()); await expect(apply()).toBeDisabled(); await undo(); assert.equal((await layer()).filters[0].parameters.seed, 0); await redo(); await reopen(precision); await values({ ...defaults, seed: 4294967295 });
  checkpoint('30 source / 26 global discovery, complete defaults/value0, exact centipercent and uint32 bounds, invalid drafts issue no writes, equivalent numeric drafts stay clean and local Reset preserves opacity');

  const localBefore = await current(), localPixels = (await exported()).data, localWrites = requests.length;
  await page.evaluate(() => { window.__noiseEntropyCalls = 0; window.__noiseEntropyMode = 'collision'; window.__noiseEntropyValue = 4294967295; window.__originalGetRandomValues = crypto.getRandomValues; Object.defineProperty(crypto, 'getRandomValues', { configurable: true, value: values => { window.__noiseEntropyCalls++; if (window.__noiseEntropyMode === 'throw') throw Error('No entropy in this deterministic test'); values[0] = window.__noiseEntropyValue; return values; } }); });
  await fields({ amount: 137.31, distribution: 'gaussian', monochromatic: false }); await pattern().click(); await values({ amount: 137.31, distribution: 'gaussian', monochromatic: false, seed: 0 });
  await page.evaluate(() => window.__noiseEntropyValue = 4294967295); await pattern().click(); await expect(seed()).toHaveValue('4294967295');
  await page.evaluate(() => window.__noiseEntropyMode = 'throw'); await pattern().click(); await expect(seed()).toHaveValue('0'); await pattern().click(); await expect(seed()).toHaveValue('1');
  await seed().fill(''); await amount().fill(''); await pattern().click(); await expect(seed()).toHaveValue('2'); await expect(amount()).toHaveValue(''); await expect(apply()).toBeDisabled();
  await seed().fill(''); await page.evaluate(() => { window.__noiseEntropyMode = 'value'; window.__noiseEntropyValue = 0; }); await pattern().click(); await expect(seed()).toHaveValue('0');
  const calls = await page.evaluate(() => window.__noiseEntropyCalls); assert.equal(calls, 6); await panel.locator('.noise-help summary').click(); await panel.locator('.noise-help summary').click(); await panel.getByLabel('Layer filter opacity', { exact: true }).fill('42'); assert.equal(await page.evaluate(() => window.__noiseEntropyCalls), calls);
  assert.deepEqual(await current(), localBefore); assert.deepEqual((await exported()).data, localPixels); assert.equal(requests.length, localWrites);
  await amount().fill('137.31'); await mutate(() => apply().click()); assert.deepEqual((await layer()).filters[0].parameters, { amount: 137.31, distribution: 'gaussian', monochromatic: false, seed: 0 }); assert.equal((await layer()).filters[0].opacity, .42);
  await page.evaluate(() => Object.defineProperty(crypto, 'getRandomValues', { configurable: true, value: window.__originalGetRandomValues }));
  checkpoint('New pattern samples once only per click, stays local with no pixels/history/requests, preserves every other draft, guarantees different seeds with max wrap/fallback, repairs invalid seeds, and commits only on explicit Apply');

  await open(vectorFixture); await add(vectors.goldens[0].parameters);
  for (const [index, golden] of vectors.goldens.entries()) {
    if (index) { await fields(golden.parameters); await mutate(() => apply().click()); }
    const expected = Buffer.from(golden.rgba), compositeExpected = Buffer.from(expected); for (let i = 0; i < expected.length; i += 4) if (!expected[i + 3]) compositeExpected.fill(0, i, i + 4);
    const actual = await exported(vectorFixture.id, `noise-vector-${golden.parameters.distribution}-${golden.parameters.monochromatic ? 'mono' : 'color'}-${golden.parameters.seed}.png`);
    assert.deepEqual(actual.data, compositeExpected);
    assert.deepEqual((await exported()).data, actual.data);
    for (const maxWidth of [32, 2400, 32]) { const preview = await native.execute('get_preview', { documentId: vectorFixture.id, maxWidth }); assert.deepEqual(await sharp(Buffer.from(preview.data, 'base64')).ensureAlpha().raw().toBuffer(), compositeExpected); }
    await mutate(() => bake().click()); const baked = await layer(), rawBaked = await sharp(await fs.readFile(path.join(native.assetsDir, baked.asset))).ensureAlpha().raw().toBuffer(); assert.deepEqual(rawBaked, expected); await undo(); await editFilter(1);
  }
  const finalVector = vectors.goldens.at(-1); await reopen(vectorFixture); assert.deepEqual((await layer()).filters[0].parameters, finalVector.parameters); const repeated = (await exported()).data;
  await open(equalFixture); await add(finalVector.parameters); assert.deepEqual((await exported()).data, repeated);
  // Source-alpha skips preserve later counter positions. Bake keeps the hidden
  // working RGB rather than applying a sampled candidate to that pixel.
  const alphaSkip = Buffer.from([255, 0, 255, 255, 255, 255]), skipProject = native.project(equalFixture.id), skipGraph = structuredClone(skipProject.states[skipProject.cursor].graph); skipGraph.layers[0].alphaAsset = await native.storeAlpha(alphaSkip, 3, 2); await native.commit(skipProject, skipGraph, 'Golden alpha skip'); await reopen(equalFixture); await mutate(() => bake().click());
  const skippedBaked = await sharp(await fs.readFile(path.join(native.assetsDir, (await layer()).asset))).ensureAlpha().raw().toBuffer(), skippedExpected = Buffer.from(finalVector.rgba); skippedExpected.set(vectors.input.slice(4, 8), 4); assert.deepEqual(skippedBaked, skippedExpected);
  checkpoint('Twelve final-map independent BigInt vectors match full exports and raw Bake bytes for both distributions/color modes and seeds0/1/max; previews/reopen/equal-source IDs repeat and alpha skips never shift later samples');

  await open(sparse); const sparseBefore = await current(); await values(defaults); await expect(apply()).toBeDisabled(); await editFilter(2); await values({ ...defaults, seed: 0, monochromatic: false }); await expect(apply()).toBeDisabled(); await editFilter(3); await values({ ...defaults, amount: 0, distribution: 'gaussian', seed: 4294967295 }); await expect(apply()).toBeDisabled(); assert.equal((await current()).revision, sparseBefore.revision);
  await editFilter(2); await amount().fill('75.25'); await mutate(() => apply().click()); const secondId = (await layer()).filters[1].id; assert.deepEqual((await layer()).filters[1].parameters, { ...defaults, amount: 75.25, seed: 0, monochromatic: false }); assert.equal((await layer()).filters[1].opacity, .4);
  await edit(sparse.id, 'update_layer_filter', { layerId: sparse.target, filterId: secondId, parameters: { distribution: 'gaussian' } }); await reopen(sparse); await editFilter(2); await values({ ...defaults, amount: 75.25, seed: 0, monochromatic: false, distribution: 'gaussian' }); await expect(apply()).toBeDisabled(); await undo(); await editFilter(2); await expect(distribution()).toHaveValue('uniform'); await redo();
  await open(alphaFixture); const alphaBefore = await current(), layerBefore = await layer(), baseline = (await exported()).data, originalView = await sourceView(alphaFixture.id, alphaFixture.target), originalMask = await sourceView(alphaFixture.id, alphaFixture.target, 'mask');
  await add({ amount: 100, distribution: 'gaussian', monochromatic: false, seed: 0 }, 50); const fractional = (await exported()).data; assert.deepEqual(alphaBytes(fractional), alphaBytes(baseline)); await amount().fill('50'); await panel.getByLabel('Layer filter opacity', { exact: true }).fill('100'); await mutate(() => apply().click()); assert.notDeepEqual((await exported()).data, fractional); await undo();
  await choose('brightness'); await panel.getByLabel('Layer filter value', { exact: true }).fill('20'); await mutate(() => addButton().click()); const ordered = (await exported()).data; await mutate(() => panel.getByRole('button', { name: 'Move filter 2 earlier', exact: true }).click()); assert.notDeepEqual((await exported()).data, ordered); await undo();
  assert.deepEqual((await layer()).mask, layerBefore.mask); assert.deepEqual((await layer()).transforms, layerBefore.transforms); assert.deepEqual((await current()).selection, alphaBefore.selection); assert.deepEqual(alphaBytes((await exported()).data), alphaBytes(baseline)); assert.equal(await sourceView(alphaFixture.id, alphaFixture.target), originalView); assert.equal(await sourceView(alphaFixture.id, alphaFixture.target, 'mask'), originalMask);
  await open(precision); await mutate(() => clear().click()); const identityBase = (await exported()).data; await add({ amount: 0, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); assert.deepEqual((await exported()).data, identityBase); await expect(page.getByLabel('Protect original pixels', { exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Brush (B)', exact: true }).click(); const identityBox = await page.locator('.artboard').boundingBox(), paintCount = requests.filter(item => item.command === 'paint_stroke').length; await page.mouse.click(identityBox.x + identityBox.width / 2, identityBox.y + identityBox.height / 2); await expect(page.getByRole('alert')).toContainText('Review Bake filters or Clear filters'); assert.equal(requests.filter(item => item.command === 'paint_stroke').length, paintCount); await dismiss(); await page.getByRole('button', { name: 'Move layer (V)', exact: true }).click();
  await mutate(() => panel.getByLabel('Enable filter 1 Add Noise', { exact: true }).click()); await expect(page.getByLabel('Protect original pixels', { exact: true })).toBeEnabled(); await open(protectedTarget); await expect(panel.getByRole('button', { name: 'New filter', exact: true })).toBeDisabled(); await open(prefix); await expect(bake()).toBeDisabled();
  checkpoint('Sparse effective defaults preserve zero/false/max without false dirty writes; partial merges retain settings/ID/opacity, order and Amount differ from opacity, source/alpha/mask/geometry stay exact, and zero Amount keeps structural protection/source guards');

  let capMode = 'missing'; const capRoute = async route => { const response = await route.fetch(), status = await response.json(); for (const backend of status.backends) if (backend.id === 'native') { if (capMode === 'missing') delete backend.layerFilterNoisePolicy; if (capMode === 'unknown') backend.layerFilterNoisePolicy = 'future-noise'; if (capMode === 'coordinates') delete backend.layerFilterCoordinates; if (capMode === 'kind') backend.layerFilterKinds = backend.layerFilterKinds.filter(kind => kind !== 'add_noise'); if (capMode === 'old-marker') { delete backend.layerFilterSpatialPolicy; delete backend.layerFilterUnsharpPolicy; } if (capMode === 'add') backend.commands = backend.commands.filter(name => name !== 'update_layer_filter'); if (capMode === 'update') backend.commands = backend.commands.filter(name => name !== 'add_layer_filter' && name !== 'import_color_lookup'); } await route.fulfill({ response, json: status }); };
  await page.route('**/api/status', capRoute); for (const mode of ['missing', 'unknown', 'coordinates', 'kind']) { capMode = mode; await reopen(caps); await values({ amount: 12.34, distribution: 'gaussian', monochromatic: false, seed: 0 }); await expect(amount()).toBeDisabled(); await expect(apply()).toBeDisabled(); await expect(panel.getByLabel('Enable filter 1 Add Noise', { exact: true })).toBeDisabled(); await expect(bake()).toBeEnabled(); await expect(clear()).toBeEnabled(); await panel.getByRole('button', { name: 'New filter', exact: true }).click(); await expect(panel.getByLabel('New layer filter kind').locator('option')).toHaveCount(mode === 'coordinates' ? 22 : 31); await panel.getByLabel('New layer filter kind').selectOption('brightness'); await expect(addButton()).toBeEnabled(); }
  capMode = 'old-marker'; await reopen(caps); await expect(amount()).toBeEnabled(); await amount().fill('125'); await mutate(() => apply().click()); await undo(); capMode = 'add'; await reopen(caps); const localRevision = (await current()).revision; await reset().click(); await values(defaults); await pattern().click(); await expect(apply()).toBeDisabled(); assert.equal((await current()).revision, localRevision); await add(); await undo(); capMode = 'update'; await reopen(caps); await expect(panel.getByRole('button', { name: 'New filter', exact: true })).toBeDisabled(); await reset().click(); await mutate(() => apply().click()); await undo(); capMode = 'full'; await reopen(caps); await choose(); capMode = 'missing'; await expect(panel.locator('.tonal-unavailable')).toContainText('required source-pixel RGB policy'); await expect(panel.getByLabel('New layer filter kind')).toBeEnabled(); await panel.getByLabel('New layer filter kind').selectOption('brightness'); await expect(addButton()).toBeEnabled(); await page.unroute('**/api/status', capRoute);
  await reopen(lifecycle); await amount().fill('150'); let pending = await hold('update_layer_filter'); await apply().click(); await pending.started; await editFilter(2, 'Brightness'); pending.release(); await settled(); await pending.done(); await expect(panel.getByLabel('Layer filter value', { exact: true })).toHaveValue('12'); await reopen(lifecycle); await undo(); pending = await hold('update_layer_filter'); await panel.getByLabel('Enable filter 1 Add Noise', { exact: true }).click(); await pending.started; await select(lifecycle.other); pending.release(); await settled(); await pending.done(); await expect(page.locator(`.layer-row[data-layer-id="${lifecycle.other}"]`)).toHaveClass(/selected/); await reopen(lifecycle); await undo(); await amount().fill('175'); pending = await hold('get_preview'); await apply().click(); await pending.started; await page.getByLabel('Open document').evaluate((element, id) => { element.disabled = false; element.value = id; element.dispatchEvent(new Event('change', { bubbles: true })); }, alternate.id); currentId = alternate.id; await settled(); await select(alternate.target); pending.release(); await settled(); await pending.done(); await expect(page.getByLabel('Open document')).toHaveValue(alternate.id); await reopen(lifecycle); await undo();
  let releaseStatus, statusStart, statusOnce = true; const statusGate = new Promise(resolve => releaseStatus = resolve), statusPending = new Promise(resolve => statusStart = resolve); await page.route('**/api/status', async route => { const response = await route.fetch(), status = await response.json(); for (const backend of status.backends) if (backend.id === 'native') delete backend.layerFilterNoisePolicy; if (statusOnce) { statusOnce = false; statusStart(); await statusGate; } await route.fulfill({ response, json: status }); }); await statusPending; await amount().fill('180'); pending = await hold('update_layer_filter'); await apply().click(); await pending.started; releaseStatus(); await expect(panel.locator('.tonal-unavailable')).toContainText('required source-pixel RGB policy'); pending.release(); await settled(); await pending.done(); await expect(amount()).toHaveValue('180'); assert.equal((await layer()).filters[0].parameters.amount, 180); await page.unroute('**/api/status');
  checkpoint('Independent Noise policy/coordinates/kind and partial commands gate only their operations; saved unsupported settings stay readable, old Gaussian and Unsharp markers are unnecessary, Reset/New pattern stay local, and late filter/layer/document/preview/policy responses cannot retarget');

  await reopen(recipe); await pattern().click(); await amount().fill('399');
  const recipeBefore = await current(), sourcePattern = await sourceView(recipe.id, recipe.target, 'layer');
  await recipes(); await dialog.getByRole('button', { name: 'Save selected layer settings', exact: true }).click(); await dialog.getByLabel('Captured recipe name').fill('Complete Noise seeds'); await dialog.locator('.recipe-steps details').first().locator('summary').click();
  await expect(dialog.locator('.recipe-steps')).toContainText('"amount":5,"distribution":"uniform","monochromatic":true,"seed":1'); await mutate(() => dialog.getByRole('button', { name: 'Save new recipe', exact: true }).click());
  const captured = (await current()).editRecipes.find(item => item.name === 'Complete Noise seeds'), capturedParameters = [defaults, { ...defaults, seed: 0, monochromatic: false }, { ...defaults, amount: 0, distribution: 'gaussian', seed: 4294967295 }];
  assert.deepEqual(captured.steps.map(step => step.args.parameters), capturedParameters); assert.equal(captured.steps[1].args.enabled, false); assert.equal(captured.steps[1].args.opacity, .4); assert.deepEqual((await current()).layers, recipeBefore.layers);
  const downloadPromise = page.waitForEvent('download'); await dialog.getByRole('button', { name: 'Export recipe', exact: true }).click(); const download = await downloadPromise, transferPath = path.join(dataDir, 'noise.prism-recipe.json'); await download.saveAs(transferPath); const transfer = JSON.parse(await fs.readFile(transferPath, 'utf8')); assert.deepEqual(transfer.steps, captured.steps);
  await dialog.getByLabel('Import recipe definition file').setInputFiles(transferPath); await mutate(() => dialog.getByRole('button', { name: 'Save imported recipe', exact: true }).click()); assert.deepEqual((await current()).editRecipes.at(-1).steps, captured.steps);
  await dialog.getByLabel('Recipe target target', { exact: true }).selectOption(recipe.other); await dialog.getByRole('button', { name: 'Validate recipe', exact: true }).click(); await expect(dialog.getByRole('region', { name: 'Recipe validation result' })).toContainText('Ready at revision'); await mutate(() => dialog.getByRole('button', { name: 'Apply recipe · 3 steps', exact: true }).click());
  assert.deepEqual((await current()).layers.find(item => item.id === recipe.other).filters.map(filter => filter.parameters), capturedParameters); assert.equal(await sourceView(recipe.id, recipe.other, 'layer'), sourcePattern);
  await close(); await undo(); assert.deepEqual((await current()).layers, recipeBefore.layers); await recipes(); await dialog.getByLabel('Recipe target target', { exact: true }).selectOption(recipe.other); await dialog.getByRole('button', { name: 'Validate recipe', exact: true }).click(); await expect(dialog.getByRole('region', { name: 'Recipe validation result' })).toContainText('Ready at revision');
  capMode = 'missing'; await page.route('**/api/status', capRoute); await expect(dialog).toContainText('required source-filter policy'); await expect(dialog.getByRole('region', { name: 'Recipe validation result' })).toHaveCount(0); await expect(dialog.getByRole('button', { name: 'Apply recipe · 3 steps', exact: true })).toBeDisabled(); await expect(dialog.getByRole('button', { name: 'Save selected layer settings', exact: true })).toBeEnabled(); await close(); await page.unroute('**/api/status', capRoute);
  checkpoint('Recipe capture materializes full saved defaults/seeds0/max and excludes New pattern drafts; transfer/order/disabled/opacity survive, equal-source replay repeats exact pixels with one Undo, and policy loss invalidates ready execution without changing recovery');

  await reopen(alphaFixture); const bakeBefore = await layer(), bakePixels = (await exported()).data; await mutate(() => bake().click()); const baked = await layer(); assert.deepEqual(baked.filters, []); assert.deepEqual((await exported()).data, bakePixels); assert.equal(baked.sourceAsset, bakeBefore.sourceAsset); assert.equal(baked.alphaAsset, bakeBefore.alphaAsset); assert.deepEqual(baked.mask, bakeBefore.mask); assert.deepEqual(baked.transforms, bakeBefore.transforms); assert.equal(await sourceView(alphaFixture.id, alphaFixture.target), originalView);
  const bakedRaw = await sharp(await fs.readFile(path.join(native.assetsDir, baked.asset))).ensureAlpha().raw().toBuffer(); for (let i = 0; i < width * height; i++) if (raw[i * 4 + 3] === 0 || alpha[i] === 0) assert.deepEqual(bakedRaw.subarray(i * 4, i * 4 + 4), raw.subarray(i * 4, i * 4 + 4));
  await page.getByRole('button', { name: 'Brush (B)', exact: true }).click(); await page.getByLabel('Brush size', { exact: true }).fill('10'); await page.getByLabel('Brush color', { exact: true }).fill('#fb22c0'); const paintBox = await page.locator('.artboard').boundingBox(); await mutate(async () => { await page.mouse.move(paintBox.x + paintBox.width * .35, paintBox.y + paintBox.height * .4); await page.mouse.down(); await page.mouse.move(paintBox.x + paintBox.width * .6, paintBox.y + paintBox.height * .4, { steps: 4 }); await page.mouse.up(); }); assert.notDeepEqual((await exported()).data, bakePixels); await undo(); assert.deepEqual((await exported()).data, bakePixels); await undo(); assert.deepEqual((await layer()).filters, bakeBefore.filters); await mutate(() => clear().click()); assert.deepEqual((await exported()).data, baseline); await undo(); await page.getByRole('button', { name: 'Move layer (V)', exact: true }).click();
  const limitFilters = (await get(limit.id)).layers[0].filters; for (const filter of limitFilters.slice(0, 2)) await edit(limit.id, 'update_layer_filter', { layerId: limit.target, filterId: filter.id, parameters: { amount: 1 } });
  await reopen(limit); await editFilter(3); await fields({ amount: 1, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); const limitBefore = await current(), limitAssets = (await fs.readdir(native.assetsDir)).sort(), writeCount = requests.filter(item => item.command === 'update_layer_filter').length;
  await apply().click(); await settled(); await expect(page.getByRole('alert')).toContainText(/work|limit|budget/i); await values({ amount: 1, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); assert.deepEqual(await current(), limitBefore); assert.deepEqual((await fs.readdir(native.assetsDir)).sort(), limitAssets); assert.equal(requests.filter(item => item.command === 'update_layer_filter').length, writeCount + 1); await dismiss();
  await reopen(lifecycle); await amount().fill('150'); pending = await hold('update_layer_filter', false); const conflictBefore = await layer(); await apply().click(); await pending.started; await edit(lifecycle.id, 'update_layer_filter', { layerId: lifecycle.target, filterId: conflictBefore.filters[0].id, parameters: { seed: 4294967295 } }); pending.release(); await settled(); await pending.done(); await expect(page.getByRole('alert')).toContainText('document changed before this color edit'); await values({ amount: 180, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); await dismiss();
  checkpoint('Explicit Bake fixes exact saved noise pixels while preserving source/alpha/hiddenRGB/masks/geometry and supports separate paint Undo; real cumulative work refusal preserves drafts/history/assets and stale seed edits refresh without retry');

  await reopen(photograph); const photoBefore = await exported(photograph.id, 'noise-photo-original.png'); await add(defaults); const uniform = await exported(photograph.id, 'noise-photo-uniform-mono-5pct-seed1.png'); assert.notDeepEqual(uniform.data, photoBefore.data); assert.deepEqual(alphaBytes(uniform.data), alphaBytes(photoBefore.data));
  await distribution().selectOption('gaussian'); await mutate(() => apply().click()); const gaussian = await exported(photograph.id, 'noise-photo-gaussian-mono-5pct-seed1.png'); assert.notDeepEqual(gaussian.data, uniform.data); assert.deepEqual(alphaBytes(gaussian.data), alphaBytes(photoBefore.data));
  await fields({ amount: 8, monochromatic: false, seed: 4294967295 }); await mutate(() => apply().click()); const colored = await exported(photograph.id, 'noise-photo-gaussian-color-8pct-seed4294967295.png'); assert.notDeepEqual(colored.data, gaussian.data); assert.deepEqual(alphaBytes(colored.data), alphaBytes(photoBefore.data));
  await reopen(photograph); await values({ amount: 8, distribution: 'gaussian', monochromatic: false, seed: 4294967295 }); assert.deepEqual((await exported()).data, colored.data); await undo(); assert.deepEqual((await exported()).data, gaussian.data); await redo(); assert.deepEqual((await exported()).data, colored.data);
  // Reduced previews must sample the full source field before resizing. Equality
  // after returning to a previous preview size detects hidden render entropy.
  const small = await native.execute('get_preview', { documentId: photograph.id, maxWidth: 64 }); await native.execute('get_preview', { documentId: photograph.id, maxWidth: 2400 }); assert.equal((await native.execute('get_preview', { documentId: photograph.id, maxWidth: 64 })).data, small.data); assert.deepEqual((await exported()).data, colored.data);
  await panel.evaluate(element => element.scrollIntoView({ block: 'start' })); await page.screenshot({ path: path.join(artifacts, 'noise-1440.png'), animations: 'disabled' }); await page.setViewportSize({ width: 900, height: 1000 }); await panel.evaluate(element => element.scrollIntoView({ block: 'start' })); await page.screenshot({ path: path.join(artifacts, 'noise-900-stack.png'), animations: 'disabled' });
  await apply().evaluate(element => element.scrollIntoView({ block: 'end' })); for (const control of [amount(), distribution(), mono(), seed(), pattern(), apply()]) await expect(control).toBeInViewport(); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); assert.ok(await page.locator('.inspector').evaluate(element => element.scrollWidth <= element.clientWidth)); await expect(panel.locator('.noise-help')).not.toHaveAttribute('open', ''); await page.screenshot({ path: path.join(artifacts, 'noise-900.png'), animations: 'disabled' });
  await panel.locator('.noise-help summary').click(); await expect(panel.locator('.noise-help')).toHaveAttribute('open', ''); for (const text of ['same pattern', 'different spread', 'unchanged hue', 'selection is ignored', 'opacity blends', 'limit refusal']) await expect(panel.locator('.noise-help')).toContainText(text); await panel.locator('.noise-help').evaluate(element => element.scrollIntoView({ block: 'center' })); await page.screenshot({ path: path.join(artifacts, 'noise-900-help.png'), animations: 'disabled' }); await panel.locator('.noise-help summary').click();
  for (const [hash, bytes] of assets) assert.deepEqual(await fs.readFile(path.join(native.assetsDir, hash)), bytes);
  for (const request of requests.filter(item => ['add_layer_filter', 'update_layer_filter'].includes(item.command))) { assert.ok(Number.isInteger(request.args.expectedRevision) && request.args.expectedRevision > 0); if (request.args.kind === 'add_noise' || request.args.parameters?.seed !== undefined) { assert.equal(request.args.value, 0); assert.ok(request.args.parameters && ['amount', 'distribution', 'monochromatic', 'seed'].every(key => key in request.args.parameters)); } }
  assert.deepEqual(failedResponses, [{ status: 400, command: 'update_layer_filter' }, { status: 409, command: 'update_layer_filter' }]); assert.deepEqual(errors, []); assert.equal(keyReads, 0); assert.equal(providerCalls, 0);
  checkpoint('Original NASA photo produces repeatable Uniform/Gaussian mono/color PNGs with exact alpha; compact1440/900 inspector keeps controls and Apply in view, expands truthful details without overflow, and every image/credential/provider boundary stays local');
  await fs.writeFile(path.join(artifacts, 'noise-browser-report.json'), JSON.stringify({ passed: checkpoints, photoSha256: photoHash, independentVectors: 'tests/fixtures/noise/final-map-goldens.json; final counter multiplier0x9e3779b9, independent BigInt mapping/byte arithmetic and certified table.', expectedRefusals: failedResponses, keyReads, providerCalls, browserErrors: errors }, null, 2)); console.log(`Noise browser checks passed: ${checkpoints.length} workflows.`);
} catch (error) { await page.mouse.up().catch(() => {}); await page.screenshot({ path: path.join(artifacts, 'noise-browser-failure.png'), animations: 'disabled' }).catch(() => {}); console.error('Alerts:', await page.getByRole('alert').allTextContents()); console.error('Browser errors:', errors); throw error; }
finally { await browser.close(); await companion.close(); await fs.rm(dataDir, { recursive: true, force: true }); }
