// Independently authored test reference. No production/prototype imports.
// Keep reduced rational geometry, rather than the runtime's simplified
// integer numerator, so algebra and rounding are checked independently.
export const PHOTO_FILTER_DEFAULTS = Object.freeze({ color: '#ff9500', density: 25, preserveLuminosity: true });
const weights = [2126n, 7152n, 722n];
const gcd = (a, b) => { a = a < 0n ? -a : a; b = b < 0n ? -b : b; while (b) [a, b] = [b, a % b]; return a; };
const fraction = (n, d = 1n) => {
  n = BigInt(n); d = BigInt(d);
  if (!d) throw Error('Zero rational denominator');
  if (d < 0n) { n = -n; d = -d; }
  const g = gcd(n, d); return { n: n / g, d: d / g };
};
const add = (a, b) => fraction(a.n * b.d + b.n * a.d, a.d * b.d);
const subtract = (a, b) => fraction(a.n * b.d - b.n * a.d, a.d * b.d);
const multiply = (a, b) => fraction(a.n * b.n, a.d * b.d);
const divide = (a, b) => fraction(a.n * b.d, a.d * b.n);
const compare = (a, b) => a.n * b.d < b.n * a.d ? -1 : a.n * b.d > b.n * a.d ? 1 : 0;
const luma = rgb => divide(rgb.reduce((sum, c, i) => add(sum, multiply(c, fraction(weights[i]))), fraction(0)), fraction(10000));
const byte = value => {
  if (compare(value, fraction(0)) < 0 || compare(value, fraction(255)) > 0) throw Error('Reference left RGB8 gamut');
  return Number((2n * value.n + value.d) / (2n * value.d));
};
export const photoFilterRationalEqual = (a, b) => compare(a, b) === 0;

export function photoFilterReferenceStages(rgb, parameters = {}) {
  const { color = PHOTO_FILTER_DEFAULTS.color, density = PHOTO_FILTER_DEFAULTS.density,
    preserveLuminosity = PHOTO_FILTER_DEFAULTS.preserveLuminosity } = parameters;
  if (typeof color !== 'string' || color.length !== 7 || !/^#[0-9a-f]{6}$/i.test(color) ||
      typeof density !== 'number' || !Number.isFinite(density) || density < 0 || density > 100 || Math.round(density * 100) / 100 !== density ||
      typeof preserveLuminosity !== 'boolean' || !Array.isArray(rgb) || rgb.length !== 3 || !rgb.every(c => Number.isInteger(c) && c >= 0 && c <= 255))
    throw Error('Invalid Photo Filter reference input');
  const amount = fraction(Math.round(density * 100), 10000), original = rgb.map(c => fraction(c));
  const filter = [1, 3, 5].map(index => fraction(parseInt(color.slice(index, index + 2), 16), 255));
  const transmitted = original.map((c, i) => multiply(c, add(subtract(fraction(1), amount), multiply(amount, filter[i]))));
  const originalLuma = luma(original), transmittedLuma = luma(transmitted);
  let output, fitted = false, zeroTransmission = false;
  if (!preserveLuminosity) output = transmitted;
  else if (transmittedLuma.n === 0n) { output = original; zeroTransmission = true; }
  else {
    const normalized = transmitted.map(c => multiply(c, divide(originalLuma, transmittedLuma)));
    const chroma = normalized.map(c => subtract(c, originalLuma));
    let factor = fraction(1);
    for (const c of chroma) if (c.n !== 0n) {
      const available = c.n > 0n ? subtract(fraction(255), originalLuma) : subtract(fraction(0), originalLuma);
      const candidate = divide(available, c);
      if (compare(candidate, factor) < 0) factor = candidate;
    }
    fitted = compare(factor, fraction(1)) < 0;
    output = chroma.map(c => add(originalLuma, multiply(factor, c)));
  }
  return { bytes: output.map(byte), exact: output, originalLuma, outputLuma: luma(output), fitted, zeroTransmission };
}

export const photoFilterReference = (rgb, parameters = {}) => photoFilterReferenceStages(rgb, parameters).bytes;

// Literal expectations precede the reference comparison. They are not
// generated by the implementation under test or calculated at import time.
export const PHOTO_FILTER_GOLDENS = Object.freeze([
  { name: 'default warm neutral', rgb: [128, 128, 128], parameters: {}, expected: [141, 126, 106] },
  { name: 'default skin-like color', rgb: [173, 116, 84], parameters: {}, expected: [188, 113, 69] },
  { name: 'default gamut fit', rgb: [255, 255, 0], parameters: {}, expected: [255, 242, 129] },
  { name: 'near black preserved', rgb: [1, 1, 1], parameters: {}, expected: [1, 1, 1] },
  { name: 'black fixed', rgb: [0, 0, 0], parameters: {}, expected: [0, 0, 0] },
  { name: 'white fixed', rgb: [255, 255, 255], parameters: {}, expected: [255, 255, 255] },
  { name: 'colored attenuation', rgb: [128, 128, 128], parameters: { color: '#ff8000', density: 25, preserveLuminosity: false }, expected: [128, 112, 96] },
  { name: 'white without preservation', rgb: [255, 255, 255], parameters: { color: '#ff8000', density: 25, preserveLuminosity: false }, expected: [255, 223, 191] },
  { name: 'neutral attenuation', rgb: [128, 128, 128], parameters: { color: '#000000', density: 25, preserveLuminosity: false }, expected: [96, 96, 96] },
  { name: 'full density black fallback', rgb: [13, 127, 253], parameters: { color: '#000000', density: 100, preserveLuminosity: true }, expected: [13, 127, 253] },
  { name: 'full density black attenuation', rgb: [13, 127, 253], parameters: { color: '#000000', density: 100, preserveLuminosity: false }, expected: [0, 0, 0] },
  { name: 'occupied channel annihilation', rgb: [255, 0, 0], parameters: { color: '#00ffff', density: 100, preserveLuminosity: false }, expected: [0, 0, 0] },
  { name: 'occupied channel fallback', rgb: [255, 0, 0], parameters: { color: '#00ffff', density: 100, preserveLuminosity: true }, expected: [255, 0, 0] },
  { name: 'annihilation endpoint approach', rgb: [0, 127, 91], parameters: { color: '#ff0000', density: 99.99, preserveLuminosity: true }, expected: [0, 127, 91] },
  { name: 'annihilation endpoint', rgb: [0, 127, 91], parameters: { color: '#ff0000', density: 100, preserveLuminosity: true }, expected: [0, 127, 91] },
  { name: 'three exact half ties', rgb: [13, 127, 253], parameters: { color: '#000000', density: 50, preserveLuminosity: false }, expected: [7, 64, 127] },
  { name: 'ten percent exact half', rgb: [0, 1, 255], parameters: { color: '#000000', density: 10, preserveLuminosity: false }, expected: [0, 1, 230] },
  { name: 'authored density before half', rgb: [0, 1, 255], parameters: { color: '#000000', density: 9.99, preserveLuminosity: false }, expected: [0, 1, 230] },
  { name: 'authored density after half', rgb: [0, 1, 255], parameters: { color: '#000000', density: 10.01, preserveLuminosity: false }, expected: [0, 1, 229] },
  { name: 'zero density exact identity', rgb: [13, 127, 253], parameters: { color: '#0100ff', density: 0, preserveLuminosity: false }, expected: [13, 127, 253] },
]);

// PNG hashes describe the already inspected design artifacts, not a portable
// encoder contract. Browser/native tests should compare decoded RGB bytes.
export const PHOTO_FILTER_PHOTO_GOLDENS = Object.freeze({
  source: { path: 'tests/fixtures/tonal-color/astronaut.png', width: 512, height: 512,
    sha256: '88431cd9653ccd539741b555fb0a46b61558b301d4110412b5bc28b5e3ea6cb5' },
  cases: [
    { parameters: PHOTO_FILTER_DEFAULTS, pngSha256: 'b04f3ba29acc7f90d027a8fb4dfa1402935ebbeee645481175f8ba437b35e1b7' },
    { parameters: { color: '#ff9500', density: 25, preserveLuminosity: false }, pngSha256: '9c2bd9609b4939ba8b7c4396d867c75dfb9a4ac69919535bcbaadb56647eed12' },
    { parameters: { color: '#5080ff', density: 25, preserveLuminosity: true }, pngSha256: '2bc0f949bb90dfbab05eb9ffa55bb8564c6c2cad4ee5702ad627af1655f34693' },
  ],
});
